### PR TITLE
New next and previous buttons

### LINKED ISSUE #372: Create a button for the > next chapter segment
Chethan made a great point on Slack:

> Would be great to have a much more clear indicator for the next chapter/segment. Right now the text link does not feel like it gives great clarity on how to navigate to the next page.

image (1)

### PR DESCRIPTION
**Pull request by GBKS**
Added a new include for buttons at the bottom of each page to get to the next and previous pages. Added them to the pages in the "Getting started" section for now. If we like this solution, we can add it to other pages as well.

[Preview](https://deploy-preview-422--sad-borg-390916.netlify.app/guide/getting-started/software/) (see bottom of the page).

Closes #372

### CODE REVIEW

**Comment by pavlenex** [comment]
It doesn't appear on top-level pages like `Introduction` or `Getting Started` or `Onboarding` is this on purpose if so, why?

**Comment by GBKS** [comment]
@pavlenex I just added it to a few pages for now to see if we generally like this solution. If so, we can add it to all the other pages also, but I thought it might best to get some feedback first as it's a bunch of manual work.

**Comment by pavlenex** [comment]
Got it @GBKS, sorry haven't looked at the diffs for this one, just tested it out. 

tACK on both mobile and desktop.

**Review by pavlenex — APPROVED** [review]

**Comment by GBKS** [comment]
@pavlenex I added the buttons to the remaining files.

**Review by pavlenex — APPROVED** [review]
tACK

**Pull request merged**
