### PR TITLE
Adds a new /calendar page

### PR DESCRIPTION
**Pull request by GBKS**
As discussed on Slack, this creates a new page for just the calendar. The calls we organize are pretty important, but the calendar info so far has been somewhat hard to find at the bottom of the Contribute page.

This new page also more explicitly describes what types of calls we organize.

Also required a slight styling tweak to the footer, as this change introduced a new top-level "Calendar" nav option. This didn't totally fit in the desktop footer anymore, so I just switched desktop to also use the mobile layout.

### CODE REVIEW

**Comment by Bosch-0** [comment]
Awesome, looks great to me! Few minor suggestions:

- The CTA looks a little awkwardly placed and I'm not sure the second sentence after it fits in well - maybe it could be slightly reworded? 
- We could add links to the 4 call categories listed that opens the GitHub meta repo issues page with search filters applied based on labels. 
- The **Adding your own event** section does not mention anything about where to go to create your own event (GitHub). Maybe add one point at the top that mentions we use GitHub issues to create and track calls. 

Otherwise this looks great :)

**Comment by GBKS** [comment]
@Bosch-0 good feedback, I'll try to address this. Just one question, what do you mean by awkward placement of the CTA? Logically within the text? Or visually in the layout?

**Comment by pavlenex** [comment]
Should we make our newsletter a bit more prominent? I think `subscribe` is a wrong CTA that may lead someone who's not familiar with a cryptic page. Actually, what user should do is `copy` the url and paste into their own calendar? I wonder if there's a way to `download` ical file and open it into calendar, that cta would be way more helpful, but probably not possible.

**Comment by GBKS** [comment]
@Bosch-0 I just added those links, removed the button (the functionality for subscribing via a button doesn't even exist), and did some rewording of the intro and the section about adding your own events.

@pavlenex Good point, I removed the subscribe button. for the newsletter, I think we need to revise the home page with more obvious call-to-actions (in a separate PR).

**Review by pavlenex — APPROVED** [review]
LGTM

**Comment by Bosch-0** [comment]
Ashame there isn't a widely used URI for calenderers, would make the CTA more useful. Agree with Pav's rationale there. Everything LGTM

ACK

**Review by Bosch-0 — APPROVED** [review]

**Pull request merged**
