### PR TITLE
Fix for #124

### PR DESCRIPTION
**Pull request by sbddesign**
I'm replacing the social preview image in the `/assets/images`  directory with an image like the one we've been discussing in the issue thread. This has been slightly re-colored in nit-picky graphic designer ways and has had its dimensions adjusted accorded to the GitHub specs.

### CODE REVIEW

**Review by pavlenex — APPROVED** [review]
I've added it to my fork just for testing looks good!

Screenshot 2021-03-16 at 17 51 32

**Review by johnsBeharry — APPROVED** [review]
tACK

---

One thing that may be out of scope for this issue, but we may want to consider in a follow up is using relative paths for the images in the meta tags as it makes testing difficult. ref: `_config.yml:63`

## Output
```html
<meta property="og:url" content="/index" />
<meta property="og:site_name" content="Bitcoin Design" />
<meta property="og:image" content="https://bitcoindesign.github.io/Guide/assets/images/bitcoin-design-preview.jpg" />
<meta name="twitter:card" content="summary" />
<meta property="twitter:image" content="https://bitcoindesign.github.io/Guide/assets/images/bitcoin-design-preview.jpg" />
<meta property="twitter:title" content="Bitcoin Design" />
<meta name="twitter:site" content="@Bitcoin Design" />
```

**Comment by GBKS** [comment]
@pavlenex the guide intro page already has its own preview image, using the Bitcoin Island visual that's on the page itself (https://bitcoin.design/assets/images/guide/bitcoin-island-preview.jpg).

@johnsBeharry good catch, we should update that a link separately.

**Comment by sbddesign** [comment]
Does the image also need to be defined as the preview in the repository settings?

**Comment by pavlenex** [comment]
It does, someone with the access should add it to the repo, cc @GBKS

**Comment by GBKS** [comment]
Just updated the repo preview image.

**Pull request merged**
