### PR TITLE
Add home page banner full-width background images option

### LINKED ISSUE #260: Add another background image option to the home page banner theme
Currently, only one image can be defined, for the right side of the banner. Theme design proposals I've seen also want to add background images to the left side (instead of just flat color). So I suggest making the theme a bit more flexible by by adding a background image option to the left side.

The only tricky part here is mobile. On mobile, the text area is not a nice square but a rectangle (based on screen size). So a background image might be cut off or not stretch the whole height. I'd solve this by ensuring the background image fades out into the background color (top or bottom, based on the flip option for mobile).

### PR DESCRIPTION
**Pull request by GBKS**
To accommodate new banner design by Rama, which is also implemented here to showcase this functionality.

Don't merge this until the banner theme is actually finalized. Need to review this with Rama.

Closes #260

### CODE REVIEW

**Comment by ConorOkus** [comment]
LGTM

**Comment by danielnordh** [comment]
Looks good to me!

**Comment by johnsBeharry** [comment]
I'm really digging the mixed style here. I'm curious why the statue person is not interested though 😅

How do credits work for such kind of artwork since it's a composite? Do we need references to the source images?

**Comment by GBKS** [comment]
@johnsBeharry the author name is always linked to the issue in which the design was proposed. In there, we should ensure to properly attribute all images used.

**Comment by GBKS** [comment]
Updated with design tweaks by Rama, a proper name for the theme ("The Meta-Future"), and the correct link to the issue where Rama proposed the design. Should be good to go now if people like it.

**Review by danielnordh — APPROVED** [review]
Looks good to me!

**Review by ConorOkus — APPROVED** [review]

**Pull request merged**
