### PR TITLE
[WIP] Create target-audience.md

### LINKED ISSUE #51: Define audience for the guide
A common understanding of the audience is helpful for writers to adopt appropriate language and weight off what to include and exclude.

This [Google doc](https://docs.google.com/document/d/1XCd8dxZIt6dXNtanXzPlizhgvuTD4Tn_Rk9j2AgcJUk/edit?usp=sharing) started by @johnsBeharry and I is a starting point we can iterate and then turn into a PR.

### PR DESCRIPTION
**Pull request by pavlenex**
This is literally copy-pasted version of this [Google Document.](https://docs.google.com/document/d/1XCd8dxZIt6dXNtanXzPlizhgvuTD4Tn_Rk9j2AgcJUk/edit)
The goal of this PR is to kick things off, lay out the structure and engage contributors into filling the gaps.

Feel free to suggest edits, comment on the structure, etc. This is a very very rough draft.

Once fully polished:
Closes #51

### CODE REVIEW

**Comment by GBKS** [comment]
Thanks @pavlenex for breathing life back into this one. This originally came up, IIRC, from a question by @ConorOkus. I believe it's also relevant to the discussions [here](https://github.com/BitcoinDesign/Guide/pull/210#pullrequestreview-630160379), about the backup page speaking to the end-user vs a product builder.

**Comment by danielnordh** [comment]
Is it supposed to be linked to from the 'Contribute' section, and be listed in the side nav?
I can't find a link to the page.

**Comment by GBKS** [comment]
@danielnordh try [this link here](https://deploy-preview-233--sad-borg-390916.netlify.app/guide/contribute/target-audience/).

Looks like links on PR preview pages are now messed up and always link to bitcoin.design instead of keeping you on that preview domain. A side effect of fixing the canonical URLs. Will have to review this.

**Comment by GBKS** [comment]
If we don't want to have a full page on this topic, we can just expand the `Know your reader` paragraph in the [content guidelines page](https://bitcoin.design/guide/contribute/content-guidelines/#know-your-reader) a bit further.

**Comment by pavlenex** [comment]
> Is it supposed to be linked to from the 'Contribute' section, and be listed in the side nav?

@danielnordh Yes, I haven't done any navigation additions yet it seems. 

> I also feel however, that as a community we are likely to create content that is relevant, and needed, for end users.

I agree, I assume that's what we meant with `Bitcoiners1` persona?

@danielnordh if you have any concrete ideas, feel free to take over or suggest them, I just copy-pasted the work from Google Doc so we can keep the ball rolling, it needs a bit more work that's for sure.

**Comment by pavlenex** [comment]
Considering condensing this for now to a simple paragraph in the https://bitcoin.design/guide/contribute/content-guidelines/#speak-to-the-reader since there's no major consensus to proceed with this in-depth for now. It's getting clearer at this point that we write for designers, developers, and sometimes even users who can benefit from itit.

**Comment by GBKS** [comment]
@pavlenex I created a PR with that minor update to the "Know your reader" paragraph in the "Content guidelines" page. See #263.

Let's get some comments on whether that minor update is enough or we need this bigger page. I'm voting for the minor update.

This audience definition is just for the guide (IMHO). If we do workshops or other projects, they can have other audiences, whether that's a subset or a different group of people. So I'd keep this one fairly simple.

**Pull request closed without merging**
