### PR TITLE
Dissolve foundations section, move pages to the Designing Bitcoin Products section

### PR DESCRIPTION
**Pull request by GBKS**
Per #257.

[Preview](https://deploy-preview-346--sad-borg-390916.netlify.app/guide/designing-products/principles/).

I placed the pages in an order that made sense to me, but curious to hear if you agree.

### CODE REVIEW

**Comment by Bosch-0** [comment]
This is the order I would of used, makes the most sense.

Only change required is a link on chapter front page to principles and wallet interoperability pages.

**Comment by GBKS** [comment]
> Only change required is a link on chapter front page to principles and wallet interoperability pages.

Good catch, just added those.

**Review by Bosch-0 — APPROVED** [review]

**Comment by danielnordh** [comment]
This is great. ACK.

**Review by danielnordh — APPROVED** [review]
Order makes sense to me.
Checked chapter progression links from surrounding pages.
Looks good to go.

**Review by pavlenex — APPROVED** [review]
Good idea, ACK.

**Pull request merged**
