### PR TITLE
Banner Image for Payment Request Page 

### PR DESCRIPTION
**Pull request by IamSanjana**
Fixes Issue #645

### CODE REVIEW

**Review by GBKS — CHANGES_REQUESTED** [review]
Thank you for getting hands-on and creating this PR. Adding a header image to a page is unfortunately a bit more involved than just uploading it. This is probably not obvious from the [documentation](https://bitcoin.design/guide/contribute/illustration-guidelines/), so I'll outline it here real quick:

A header image needs to be uploaded in 4 different sizes, to look good on mobile and despot, as well as normal and retina screens. The sizes are typically:
- 3200x1200px
- 1600x600px
- 800x400px
- 400x200px

In addition, the page needs a preview image. This is what is shown when the link to the page gets shared on social media. This image needs to be 1200x630px.

You can look at other pages for examples, like the [Activity page folder](https://github.com/BitcoinDesign/Guide/tree/master/assets/images/guide/payments/activity).

Lastly, the image needs to be included in the markdown file of the page. You can also see what this looks like in the [Activity page markdown file](https://github.com/BitcoinDesign/Guide/blob/master/guide/payments/activity.md?plain=1), on lines 9, and lines 63 to 72.

Too complicated? All good, just share the design source files and we'll set it up for you.

**Comment by IamSanjana** [comment]
@GBKS Thank you so much for mentioning the changes and the steps.
I will follow up with them and try to deliver the desired changes.

**Comment by IamSanjana** [comment]
Changes made.

**Review by GBKS — DISMISSED** [review]

**Comment by GBKS** [comment]
Sorry for the delay. Just went through it all and everything looks correct.

**Review by GBKS — APPROVED** [review]

**Pull request merged**
