### PR TITLE
Added home page banner theme for HereComesBitcoin

### PR DESCRIPTION
**Pull request by Abhijay007**
Implemented HereComes Bitcoin theme Banner, Here's a link to the issue proposal : https://github.com/BitcoinDesign/Guide/issues/1110

pixelcut-export

### CODE REVIEW

**Comment by GBKS** [comment]
> think the images need better compression, as mentioned in the guide. However, when I followed the steps—specifically, running the site locally—the images should have been automatically compressed. I'm not sure why this isn't working. There might be an action/script that performs this task, but it doesn't seem to be triggered in my case, any suggestions on how I could run this manually?

Good catch. We disabled the auto-compression recently because it caused lots of other issues (we have to update the docs). 

You are right, that the images need compression still (I use [ImageOptim](https://imageoptim.com/mac), which is super fast), they are also way bigger than necessary. Here are sizes I'd recommend:

- HCB-Banner.png - 720x720
- HCB-Banner@2x.png - 1440x1440
- HCB-Banner-Mobile.png - 400x400
- HCB-Banner-Mobile@2x.png - 800x800

Otherwise everything looks great.

**Comment by Abhijay007** [comment]
> > think the images need better compression, as mentioned in the guide. However, when I followed the steps—specifically, running the site locally—the images should have been automatically compressed. I'm not sure why this isn't working. There might be an action/script that performs this task, but it doesn't seem to be triggered in my case, any suggestions on how I could run this manually?
> 
> Good catch. We disabled the auto-compression recently because it caused lots of other issues (we have to update the docs).
> 
> You are right, that the images need compression still (I use [ImageOptim](https://imageoptim.com/mac), which is super fast), they are also way bigger than necessary. Here are sizes I'd recommend:
> 
> * HCB-Banner.png - 720x720
> * [HCB-Banner@2x.png](mailto:HCB-Banner@2x.png) - 1440x1440
> * HCB-Banner-Mobile.png - 400x400
> * [HCB-Banner-Mobile@2x.png](mailto:HCB-Banner-Mobile@2x.png) - 800x800
> 
> Otherwise everything looks great.

Thanks for the feedback @GBKS, but when I update them to these sizes, the images become blurry for me 😅. Do you know of any tools that can help generate high-quality images at those sizes?

**Comment by GBKS** [comment]
> when I update them to these sizes, the images become blurry

I am not sure how that is possible. Can you share a screenshot maybe?

**Comment by Abhijay007** [comment]
> > when I update them to these sizes, the images become blurry
> 
> I am not sure how that is possible. Can you share a screenshot maybe?

sure

**Comment by Abhijay007** [comment]
> > when I update them to these sizes, the images become blurry
> 
> I am not sure how that is possible. Can you share a screenshot maybe?

as you can see here it's for mobile view 400x400  in png format : 

Group 29

**Comment by GBKS** [comment]
> as you can see here it's for mobile view 400x400 in PNG format: it get's blurry.

The vast majority of mobile phones will load the 2x version, which is 800x800, and should look crisp on retina screens.

**Comment by Abhijay007** [comment]
> > as you can see here it's for mobile view 400x400 in PNG format: it get's blurry.
> 
> The vast majority of mobile phones will load the 2x version, which is 800x800, and should look crisp on retina screens.

it is getting blurry for even 800x800

**Comment by GBKS** [comment]
What phone do you preview with?

**Comment by Abhijay007** [comment]
> What phone do you preview with?

I am trying via inspect

**Comment by GBKS** [comment]
> I am trying via inspect

Try to preview it on an actual phone.

**Comment by Abhijay007** [comment]
> > I am trying via inspect
> 
> Try to preview it on an actual phone.

sure

**Comment by Abhijay007** [comment]
> Here's the logic:
> 
> * An iPhone 15 (using that as a reference phone) has a logical resolution of 393x852, and a physical resolution of 1179x2556, for a pixel ratio of 3.
> * Logical resolution is what the software uses for its math, physical resolution is the actual number of pixels on the display.
> * So the image will never be rendered larger than 393 (logical) pixels in width. Originally, all screens had a pixel ratio of 1, today many laptops and desktops still do, and that's what the regular images are optimized for.
> * With retina screens, we also have higher pixel ratios, and that's where the 2x images come in (393 becomes 786). They are optimized for a pixel ratio of 2. We could go higher, but it's useless since our eyes cannot tell more detail than 2 (hence the term retina screen).
> * 393 and 786 are weird numbers, so we just use 400 and 800 (for the mobile regular and 2x images).
> 
> Hope that makes sense.

Thanks for this, I will update those images

**Comment by Abhijay007** [comment]
@GBKS I resized the images as instructed but when I check the deployed version on my mobile device and on my desktop it looks blurry, reducing its size also reduced its pixel, I don't know how to fix this, in the link above I provided access to the figma file can you please download those images and see if it's also blurry for you?

**Comment by GBKS** [comment]
Here's a screenshot of the deploy preview on my laptop. Looks crisp. Can you please share a screenshot so I can better understand what you see?

Screen Shot 2024-09-02 at 15 18 25

**Comment by Abhijay007** [comment]
> Here's a screenshot of the deploy preview on my laptop. Looks crisp. Can you please share a screenshot so I can better understand what you see?
> 
> Screen Shot 2024-09-02 at 15 18 25

yea it is looking nice 

--------------------------------------------------------------------------

can you please check it once for mobile devices as well?

| Mobile Screenshot  | 
|:-------------------------:|
WhatsApp Image 2024-09-02 at 18 57 09|

If it works fine for you, we can go ahead and merge it, as there might be an issue on my end. Also, could you please compress these images? I don't have access to the tool you shared earlier, [ImageOptim](https://imageoptim.com/mac).

**Comment by GBKS** [comment]
Thanks for the screenshot. I figured out what it is and [created a PR](https://github.com/BitcoinDesign/Guide/pull/1114) that will address it. Your images are fine and will look crisp once this other PR is merged.

Can you please compress the images? ImageOptim tells me that they can be reduced by ~70% without quality loss.

**Review by GBKS — APPROVED** [review]
Looks great. Thanks for creating this banner and working through my image feedback.

**Pull request merged**
