### PR TITLE
Add animation support via Lottie to the home page banner

### PR DESCRIPTION
**Pull request by GBKS**
Just testing how complex it would be to implement [Lottie](https://airbnb.design/lottie/) for animations in the home page banner. This test breaks browsing other banners, just meant to be an exploration.

Used [this graphic](https://twitter.com/CalumAWatt/status/1496035466805661696?s=20) for the test. Separated layers, quickly animated in AfterEffects, exported via BodyMovin.

Overall, I think it works well. If we want to do this, we need to do a proper implementation that only loads the Lottie library when required, fix the banner theme navigation, etc.

👜[Preview](https://deploy-preview-756--sad-borg-390916.netlify.app)🧶

### CODE REVIEW

**Comment by pavlenex** [comment]
Looks really cool and playful, love it.

**Comment by GBKS** [comment]
Once this is done, we can also add the animation to Jessica's banner. Andy shared the Lottie file, which is [here](https://assets1.lottiefiles.com/private_files/lf30_1t3b29q1.json).

**Comment by GBKS** [comment]
Did a few things in the latest commit:
- Lottie is now dynamically loaded when the currently active banner needs it.
- Deleted the temporary astronaut animation I had used for testing.
- Implemented the Lottie animation for Jessica's banner. This needs fixing though. The static image had a white border that is missing in the animation, and some animation elements are images and should be vectors (for proper retina scaling and best file size).

I'll talk to Andy about the last point. If this ends up being more problematic, I'll remove the animation and turn this into a PR that only focuses on the technical implementation.

**Comment by GBKS** [comment]
I removed the update to animate Jessica's banner for now since the files still need optimization. This way we can already merge the animation functionality without having to wait for the optimization. Requesting a review now.

**Review by sbddesign — COMMENTED** [review]
Thanks for getting this started! Counter-proposal: I took your work from this branch and developed it further in my own branch to apply more generally to the entire site. Requesting review on #805

**Comment by GBKS** [comment]
@sbddesign is expanding on this PR in #805 . We can leave this PR open for now and close it when the other is done.

**Comment by GBKS** [comment]
Closing this one in favor of #805.

**Pull request closed without merging**
