### PR TITLE
Updated Slack Invite Links

### PR DESCRIPTION
**Pull request by mikehuntemann**
Invite link was no longer working: "This link is no longer active"

### CODE REVIEW

**Review by johnsBeharry — APPROVED** [review]

**Comment by moneyball** [comment]
Why don't we just point to http://www.bitcoindesigners.org/ so we don't have to maintain multiple Slack invite links?

Although, somehow, the link does not expire until the year 3019, so I don't think any of us will be around the next time we need to update the link...
Screen Shot 2020-09-22 at 9 40 04 AM

So, ACK.

**Comment by johnsBeharry** [comment]
@moneyball I wasn't aware of this url. Is it one you own?

**Comment by moneyball** [comment]
It is the URL we launched with, found here:
https://medium.com/@squarecrypto/bringing-together-the-bitcoin-design-community-b89e5fbe080f

**Comment by johnsBeharry** [comment]
Ah ok - didn't notice. If it's been published elsewhere we can use it as the standard invite link going forward but I'll close this PR now as its already merged.

**Pull request merged**
