### PR TITLE
Added ⚡️ content to `Designing Bitcoin Products` > `Usage life cycle`

### PR DESCRIPTION
**Pull request by GBKS**
Addresses #399.

👶🏻[Check the preview](https://deploy-preview-491--sad-borg-390916.netlify.app/guide/designing-products/usage-life-cycle/)🧓🏻

### CODE REVIEW

**Review by pavlenex — APPROVED** [review]
LGTM

The only nitpick I have is that 

>  “Is this a convenient way to get done what I want to do?”

sounds odd to me.

**Comment by GBKS** [comment]
@pavlenex since you approved, I assume that nit is no blocker? The language is def a bit casual, but not a big issue to me. So your call.

**Comment by pavlenex** [comment]
> @pavlenex since you approved, I assume that nit is no blocker? The language is def a bit casual, but not a big issue to me. So your call.

Yup, not a blocker at all, good to go imo.

**Comment by GBKS** [comment]
@pavlenex thanks for the review, going to merge this now.

**Pull request merged**
