### PR TITLE
Send screen highlighting high fees to the user

### LINKED ISSUE #456: Recommend warning users if fee estimation or selected fee is too high
**Describe your content request**

Hello, I would like to request an update to the [sending bitcoin page](https://bitcoin.design/guide/payments/send/) page so it recommends warning users that the transaction fee is too high.

5jsb2d

**Link to the page**
- https://bitcoin.design/guide/payments/send/

**Why would you like to change the content?**
In the events that the fee estimator is not providing accurate results, or if the user chooses to input their own custom fee, the application should inform them that the fees are too damn high.

An example of user error could be mistaking the custom fee estimation for the amount being sent. Seen a story about this somewhere on the internets. Another more likely possibility is the fee estimation not being optimised, or in fact broken/offline which can be a dangerous situation if the user depends on these automatic calculations and does not understand what "normal" fees are.

**Suggestions**
On the "[Setting the transaction fee](https://bitcoin.design/guide/payments/send/#setting-the-transaction-fee)" section:

- Add do/don'ts warn the user that they may be overpaying if the estimated fee, or custom fee is higher than some amount (lets discuss this).

On the "[Reviewing and approving the payment](https://bitcoin.design/guide/payments/send/#reviewing-and-approving-the-payment)" section:

- Add do/don't for showing a warning about fee's being too high before transaction is broadcasted
- Update/Add image to show the same warning

**Additional context**

Suggestion from @patestevao, takeaway from her [BitcoinUX research](https://github.com/patestevao/BitcoinUX-report/blob/master/report.md).

**Content guidelines**
If you're a contributor looking to tackle the issue, you can [preview our content guidelines](https://bitcoin.design/guide/contribute/content-guidelines/).

### PR DESCRIPTION
**Pull request by GBKS**
📍[Check the preview](https://deploy-preview-825--sad-borg-390916.netlify.app/guide/daily-spending-wallet/sending/#review--approval)📌

Closes #456 along with the changes from #817.

### CODE REVIEW

**Review by pavlenex — APPROVED** [review]
LGTM, but one angle to cover would be "why" is this happening. Why are the fees higher, and  perhaps even tell people that "if transaction isn't urgent, you can wait or do XYZ" Just think it may be good to add a bit more context to it, as "fees are high" may scare people leading them into thinking that it's wallet's fault or wallet being "greedy".

**Comment by GBKS** [comment]
@pavlenex that's exactly what's in the screen. Or do you mean somewhere else?

**Comment by sbddesign** [comment]
> LGTM, but one angle to cover would be "why" is this happening. Why are the fees higher, and perhaps even tell people that "if transaction isn't urgent, you can wait or do XYZ" Just think it may be good to add a bit more context to it, as "fees are high" may scare people leading them into thinking that it's wallet's fault or wallet being "greedy".

I also think the middle image covers a lot of this information. Do you think we need more detail?

**Review by sbddesign — APPROVED** [review]
✅

**Comment by sbddesign** [comment]
This PR has 2 approvals on it, but I'm not going to merge it just yet because I feel like we're still discussing something.

**Comment by pavlenex** [comment]
Yup, let's merge this one 👍

**Pull request merged**
