### PR TITLE
Adding various YouTube video references

### PR DESCRIPTION
**Pull request by GBKS**
We have really useful videos on lots of topics. With this PR, I am adding links with thumbnails to several pages where our videos can complement the content we have.

This is currently only looking at videos the community has created. We could expand this further to videos from others (just shouldn't get over-eager and fill all pages with video links).

Keeping it as a draft for now so we can feel this out and make changes with feedback.

Preview on these pages:
- [Open design](https://deploy-preview-880--bitcoin-design-site.netlify.app/guide/getting-started/open-design/#resources)
- [Conducting research](https://deploy-preview-880--bitcoin-design-site.netlify.app/guide/designing-products/user-research/#resources)
- [Accessibility](https://deploy-preview-880--bitcoin-design-site.netlify.app/guide/designing-products/accessibility/#usability-testing-resources)
- [Payment request formats](https://deploy-preview-880--bitcoin-design-site.netlify.app/guide/how-it-works/payment-request-formats/#offers)
- [Technology primer](https://deploy-preview-880--bitcoin-design-site.netlify.app/guide/getting-started/technology-primer/#resources)

### CODE REVIEW

**Comment by GBKS** [comment]
@mouxdesign thanks for the feedback. You don't think a thumbnail with a video icon is enough of an indication that the resources are videos?

**Comment by mouxdesign** [comment]
You're welcome! I think that it's possible that when the video thumbnail is viewed on a mobile device, that image with the white triangle (play button) indicating it is a video might not be so obvious so some.  I think its more for the second thumbnail (in example below) ...or thumbnails where it is white on white. The play button is easier to miss. Hope that makes sense!  
Open design  Bitcoin Design

**Comment by GBKS** [comment]
@mouxdesign I'll merge this PR for now. I find "Resources" more appropriate because it describes both the links and the videos. If you feel strongly that it needs to be more clear that these are videos, we can open a new PR for that. For example, we could also revise the design of the play button so it has more contrast on light backgrounds. Let me know if you want to discuss/do that or not.

**Comment by mouxdesign** [comment]
Agreed. Revising the design of the play button is also good as a solution. 

Nicely done!

**Pull request merged**
