### PR TITLE
Splits pages from "Getting started" into "Designing Bitcoin products" section

### PR DESCRIPTION
**Pull request by GBKS**
Per #330.

[Preview](https://deploy-preview-333--sad-borg-390916.netlify.app/guide/designing-products/introduction/).

Updated all links and image references accordingly.

Please test this first and see how it feels, as it's a bigger architectural change.

Note that this means that there's a new section landing page that we need to write copy for and create a header image.

### CODE REVIEW

**Comment by Bosch-0** [comment]
Few things but overall LGTM!

- Need a link to designing Bitcoin products on introduction page.
- Link on why Bitcoin is unique still goes to why design for Bitcoin, should go to visual language.
- Link on visual language still goes to user research, should be Technology primer.
- Open design still links to visual language, should be user research. 
- User research links to personal finance, should be usage life cycle.
- Usage life cycle still links to common user flows, should be personal finance.

**Comment by GBKS** [comment]
@Bosch-0 thanks for the review. I pushed an update with the fixes.

**Review by Bosch-0 — APPROVED** [review]
LGTM :)

**Comment by danielnordh** [comment]
Looks good.
Would be nice to have a header on the 'Designing Bitcoin products' page: https://deploy-preview-333--sad-borg-390916.netlify.app/guide/designing-products/introduction/

**Comment by GBKS** [comment]
@danielnordh for sure. Wanna create one? Or an issue for it?

**Review by pavlenex — APPROVED** [review]
I've reviewed the section, and tested links and it seems to work OK, so tACK. 

Since it's a structural change, I suggest we don't merge it before #302 and transaction privacy, though it shouldn't touch those pages, it's best to leave it out to avoid the possible rebase mess.

**Comment by GBKS** [comment]
@pavlenex the rebase thing is tricky. Obviously don't want to create a big mess for @ConorOkus and @johnsBeharry, but we also have some other structural stuff we want to do after this PR (moving fundamentals pages around). Are we blocking other work from happening if we wait with this one? Maybe best if everyone chimes in.

**Comment by pavlenex** [comment]
@GBKS If other work depends on it, let's mege it, I don't think the work on those two PR's depends on it. I'll take care of the rebases for people if there are problems.

**Comment by pavlenex** [comment]
OK confirming there are no issues with the PR's in question after the merge, let's go 🚀

**Pull request merged**
