### PR TITLE
Add Challenge 7: Covenants for Scale

### PR DESCRIPTION
**Pull request by DanGould**
## Challenge 7: Covenants for Scale

[Covenants](https://bitcoinops.org/en/topics/covenants/) are thought to be able to scale bitcoin by allowing multiple users to share UTXOs in constructions such as [Joinpools](https://bitcoinops.org/en/topics/joinpools/). It is not yet clear how such an experience would manifest in client software. Document a high-fidelity design to explore such a user experience (including flows, costs, time, complexity, etc.) that might relieve extreme network congestion or other challenges of scale.

This idea was originally proposed [on X by @leishman](https://nitter.net/Leishman/status/1744113344729043410). One approach may be to extend the design community's [Bitcoin UI Kit](https://www.bitcoinuikit.com/).

cc @leishman @yashrajd @Foundation-Devices

### CODE REVIEW

**Comment by DanGould** [comment]
Should the chaallenge mention [transaction stacking](https://rusty.ozlabs.org/2024/01/08/txhash-tx-stacking.html)?

**Comment by GBKS** [comment]
Love it. This is definitely an advanced topic (IMHO). Would be awesome to get a working group going to create a reference design or case study.

Was just listening to a Stephan Livera [podcast on covenants](https://stephanlivera.com/episode/537/) this morning. It does sound like an important area to investigate, and if there is indeed a lack of UX work, then the design community is a good candidate to help out.

I am not fully versed on the various proposals for covenants, and what use cases each one enables. But this info could probably gathered fairly quickly. If we can identify specific use cases, those could also be added to the challenge.

**Comment by yashrajd** [comment]
This was discussed in today's Bitcoin Design Jam session. We explored the possibility of organizing a Learning Bitcoin Design session for covenants that helps designers (and others) understand covenants and its use-cases in a non-technical way.

Specifically, such a session could:
- help the community understand specific covenant-enabled use-cases that UX needs to be explored & designed
- craft a problem statement for the design challenge itself.

**Comment by DanGould** [comment]
[Cold Channels](https://nitter.net/OwenKemeys/status/1744181261864665315) may also have this quality of scale

**Comment by 0xBEEFCAF3** [comment]
Let's also not forget Vaults. Regardless of the covenant proposal many of the enable vaults. Which would be an entirely new UX

**Comment by 0xBEEFCAF3** [comment]
> Love it. This is definitely an advanced topic (IMHO). Would be awesome to get a working group going to create a reference design or case study.
> 
> Was just listening to a Stephan Livera [podcast on covenants](https://stephanlivera.com/episode/537/) this morning. It does sound like an important area to investigate, and if there is indeed a lack of UX work, then the design community is a good candidate to help out.
> 
> I am not fully versed on the various proposals for covenants, and what use cases each one enables. But this info could probably gathered fairly quickly. If we can identify specific use cases, those could also be added to the challenge.

@GBKS the best resource on the different proposals and the use cases they cover is probably https://covenants.info/

**Comment by DanGould** [comment]
> Let's also not forget Vaults. Regardless of the covenant proposal many of the enable vaults. Which would be an entirely new UX

@0xBEEFCAF3 I intentionally left vaults out because I didn't think they were a scaling proposal, which is what leishman asked for. Am I mistaken? I do agree vaults UX design would make for another excellent challenge

**Comment by GBKS** [comment]
I created an issue for a collaborating on this investigation [here](https://github.com/BitcoinDesign/Meta/issues/607). Let me know what you think. Might be helpful to move the conversation there, and keep this PR focused on the extra copy to the guide.

**Comment by DanGould** [comment]
@GBKS I like your thinking

I chose the copy as it is since the joinpools seem to be the most straightforward covenant based scaling to me whereas cold channels' & transaction scaling will take me more thought to wrap my head around. I'm most interested in getting *some* imperfect copy up on the guide and revising as conversation informs us more.

**Review by GBKS — APPROVED** [review]
ACK.

**Pull request merged**
