### PR TITLE
Split private key management section into more pages

### PR DESCRIPTION
**Pull request by GBKS**
One page per scheme instead of one page for personal and one page for shared schemes. For #280.

### CODE REVIEW

**Review by johnsBeharry — APPROVED** [review]
As it stands this seems like a fine update to push out now while #210 is in the works... but... It is going to get messy for @danielnordh so the question is who will be the one to deal with the merge conflicts that will arise.

**Comment by Bosch-0** [comment]
Really like this approach, makes things a lot cleaner. I have some suggestions however as I still think this chapter is confusing, even more so with the added bitcoin backups page. To not over complicate things I think we should merge this for now and change things in other PRs.

**Meta**
    - Management and backup are so intertwined that each scheme's page should cover backups using that respective scheme as well as the scheme hows and whats. I don't think we need a separate page called bitcoin backups which currently overlaps heavily with the chapters content. 

**Change 'Automatic cloud backup' title to 'In the cloud.'**
    - This scheme isn't always automatic - this difference can be detailed in the page. 
    - Users would read 'Private key management' then 'In the cloud' and it would be clear what this section covers.
    - Remove 'backup' - It's confusing having 'automatic cloud **backup**' then a bitcoin backups page. It just all overlaps and doesn't make sense. This page should cover the how and what's of the scheme as well as how the backup process works. 

**Change 'Manual backup' to 'Manual.'** 
    -  Remove backup for the same reason as the cloud page backup should be changed.
    -  Users would read 'Private key management' then 'Manual' and it would be clear what this section covers.

**Change 'External signing device' to 'Signing devices.'** 
    - Split this into three sections: Hardware wallets, phones, computers.  

**Change 'Key sharing' to 'Key sharding.'** 
    - This page needs a re-work as it does not correctly  communicate how this works. Sharding is the more appropriate term as keys are not being shared only pieces of a key are. These pieces also don't do any signing like the page says. I've started re-writing this [here](https://docs.google.com/document/d/1lc3Ac71iFkADEHoFChT880-aw0DA4GXUM6XpYB60f3s/edit?usp=sharing). The content in red is stuff that pertains more to backups rather than signing with keys. If we distinguish the two (with the bitcoin backups page) these details would be more relevant there. Though I think backup details should be included with the scheme as mentioned above. 

**Combine multi-key and shared multi-key pages and just call it Multi-Key.** 
    - They cover similar content and would make more sense to have them together. The distinction between using it yourself or in a shared party can be made within the page.

**Review by Bosch-0 — APPROVED** [review]

**Comment by GBKS** [comment]
@Bosch-0 good feedback. How about creating a new issue so it doesn't get lost when we merge this?

**Comment by danielnordh** [comment]
> @Bosch-0 good feedback. How about creating a new issue so it doesn't get lost when we merge this?

Thanks for the feedback. As it is all related to the Private Key Management pages, not this new backup page please open a new issue with this so we can address elsewhere.

**Review by pavlenex — APPROVED** [review]

**Comment by GBKS** [comment]
Going to merge this now. We can then address the changes right away in new issues and PRs.

**Comment by danielnordh** [comment]
This page needs to be fixed. Links are broken and list doesn't reflect new pages.

**Pull request merged**
