### PR TITLE
Add two LN related user-researches

### LINKED ISSUE #486: Add ⚡️ content to `Designing Bitcoin Products` > `User research resources`
Add Lightning-related content to the [User research resources](https://bitcoin.design/guide/designing-products/user-research/resources) page, as appropriate. This page likely needs only minor tweaks. See [notes](https://docs.google.com/document/d/1JwNSJj_2_IxUcx81cbl7sa6XdPZEGduRiprTm3Y2E4o/edit?usp=sharing) from [Jam Session #14](https://github.com/BitcoinDesign/Meta/issues/120).

Secondary, do a general review of this page (check overlap with other pages, add relevant cross-links...) and check open issues for changes on this page and implement them.

### PR DESCRIPTION
**Pull request by pavlenex**
Added two user-researches that I've read through and verified.

Arcane's LN research has been added earlier.

If anyone has any more that I should add, let me know.

closes #486

### CODE REVIEW

**Review by Bosch-0 — DISMISSED** [review]
LGTM!

**Comment by GBKS** [comment]
Not Lightning, but we should also add [Patricia's latest research](https://github.com/patestevao/BitcoinUX-report).

Only criticism would be that the Lightning scaling report is not directly user-research, but more of a technical analysis. But it's still relevant to users (fees), so we should keep it.

**Comment by pavlenex** [comment]
@GBKS I remember Patricia's long-term goal with it is to integrate the research within the guide. Is this still something we'd like to pursue? If so, how do you envision such integration?

I'll add a link to Patricia's [website](https://patestevao.com/work/bitcoin-ux-research/) instead of GH, I think it better presents information visually.

**Comment by GBKS** [comment]
@pavlenex nice, I wasn't aware she had even posted her research results on the web (was only aware of the repo).

Ideally, we could integrate her results more closely into the guide. A good starting point could be to identify key quotes from each persona and insert them into relevant pages. Also, the [Getting to know your users](https://bitcoin.design/guide/designing-products/getting-to-know-your-users/#example) page is currently relying on a made-up persona, maybe this could be refreshed with a persona Patricia identified?

**Review by GBKS — APPROVED** [review]
ACK. Looking good. Thank you for taking this one on.

**Comment by pavlenex** [comment]
Two approvals and this one was trivial, so will merge it. Thanks for prompt reviews gents. 🎩

**Pull request merged**
