### PR TITLE
Current adoption table is inconsistent

### PR DESCRIPTION
**Pull request by mutatrum**
The spacing in the satoshi / millisatoshi is the first table is inconsistent compared to what the rest of this document proposes. Unclear where the ### ### ## format is coming from.

### CODE REVIEW

**Comment by GBKS** [comment]
Good one, thanks for the PR. Netlify is throwing an error that I have not seen before, do you maybe know what might be causing it?

```
4:08:13 PM: git ref pull/956/head does not exist or you do not have permission
4:08:13 PM: Creating deploy upload records
4:08:14 PM: Failing build: Failed to prepare repo
4:08:14 PM: Failed during stage 'preparing repo': git ref pull/956/head does not exist
```

**Comment by sbddesign** [comment]
@mutatrum Thanks for the fix! We just need to troubleshoot why we're getting a deploy error. Respond here in the thread, or DM me or Christoph on Slack and we can try to help.

**Comment by mutatrum** [comment]
Ok, I created a netlify account based on my GitHub account, maybe that helped?

**Comment by mutatrum** [comment]
Not sure if this is how it should be, this spacing doesn't work for millibit and bit:

image

**Review by sbddesign — APPROVED** [review]
LGTM

**Comment by sbddesign** [comment]
> Not sure if this is how it should be, this spacing doesn't work for millibit and bit:

I guess we could reformat millibits and bits, but not sure if we need to represent those with the satcomma standard.

**Comment by sbddesign** [comment]
> Good one, thanks for the PR. Netlify is throwing an error that I have not seen before, do you maybe know what might be causing it?

@GBKS since it sounds like you're in agreement with the edit, I'm going to go ahead and merge this.

**Pull request merged**
