### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by ConorOkus**
- Fixes spacing 
- Fixes broke links

**Before**
Screenshot 2020-11-24 at 11 26 04

**After**
Screenshot 2020-11-24 at 11 46 54

### CODE REVIEW

**Comment by GBKS** [comment]
Good fixes. At some point we need to revise the CSS for page content to embed proper spacing rules for all elements. I've been waiting on that until we have more content so we can have a better understanding of the layout requirements.

I am considering removing the Figma embed here, as it allows for tracking. Something we maybe want to decide side-wide whether we allow for third-party embeds or not (or have a solution where users need to enable them). What do you think?

**Comment by ConorOkus** [comment]
Yeh would be good to tidy up the spacing as it's a bit inconsistent in places. What do you mean by tracking? 

It's a good point though because it does depend on who is managing that third party service. For example, say we had design community Youtube channel and wanted to embed some videos from there, who would manage that? 

Could get pretty complicated and the maintainers of that service would need to be active members of the community. If they disappear does that content go with them? So from that point of view, we should probably minimise the number of third party embeds

**Comment by GBKS** [comment]
By tracking I mean that Figma can track visitors because we embed their code in the site via an iframe (the can track server requests and see which URLs they come from, maybe other data as well). Just linking out to a YouTube video or playlist should be fine as those are just links.

Your point about having a plan B is right on. Wasn't there a time when YouTube took down content related to bitcoin? What's a way to account for that? Have a central Dropbox with the original videos in case the uploaded ones get taken down?

**Comment by ConorOkus** [comment]
Yeh I don't think that concerns me as much as the Figma file still existing way into the future.

Youtube is always taking down Bitcoin content to be fair. I do have the videos backed up in dropbox. Maybe the solution is to also upload on something like Vimeo as well.

**Comment by danielnordh** [comment]
ACK

**Review by GBKS — APPROVED** [review]

**Pull request merged**
