### PR TITLE
Updated fee image in 'payments/send'

### PR DESCRIPTION
**Pull request by Bosch-0**
Solves issue https://github.com/BitcoinDesign/Guide/issues/435

### CODE REVIEW

**Comment by johnsBeharry** [comment]
One of the reasons for having these other details on the image is to expose transaction fee calculation to readers. Since this content is removed from the image, perhaps we should ensure its added somewhere else?

[Transactions overview](https://bitcoin.design/guide/payments/transactions/#transaction-fee) does not currently mention this calculation.

**Review by pavlenex — APPROVED** [review]
@johnsBeharry maybe we can add a new issue to add those?

This one LGTM.

**Comment by GBKS** [comment]
@johnsBeharry it's good to know for readers (designers), but maybe not something to necessarily highlight in a mainstream UI. So how about adding it as text content?

**Review by GBKS — APPROVED** [review]

**Review by johnsBeharry — APPROVED** [review]
@GBKS ye I get the premise, I was just referencing a discussion we had about the illustrations being content too - and some content is now missing. I'm fine with an update in a follow up PR.

**Pull request merged**
