### PR TITLE
Initial merchant-section commit

### PR DESCRIPTION
**Pull request by beanandcheeseburrito**
Hey guys, sharing some progress on the merchant section. Your feedback is appreciated, still lots of exciting work ahead!

TODO:
- Fix table width
- Complete Q1+Q2 user research
- Add more descriptive summaries under titles
- Get some community feedback
- Add example images

### CODE REVIEW

**Comment by GBKS** [comment]
Great to see you get started on this here. So I don't think this is in a shape that we can consider merging as the content is a mix of your project plan, questions and interview results.

For a first page to include in the guide, I'd maybe focus on summarizing the interview results (with a link to an external repo that explains the process and data - without compromising participant privacy of course). From those results, you could generate a handful of personas that could be used by teams in their design processes (I think this came up in the last Galoy call).

The project plan and such I would also keep in that external repo, some of it probably as issues as they represent tasks.

**Review by GBKS — CHANGES_REQUESTED** [review]
Left some feedback in [a comment](https://github.com/BitcoinDesign/Guide/pull/741#issuecomment-1108312603).

**Comment by sbddesign** [comment]
Thanks @beanandcheeseburrito! This page seems more project management focused. I see this as being the sort of thing we use in the background to plan out this project -- not necessarily something that goes into the front-end of the Guide.
  
I'd suggest we take a step back and do more of this work in Google Drive (or whatever text editor). As brand new content, it will be probably go through a ton of discussion and iteration. Once it's gotten through that phase, it will be easier to get the PR merged.

**Comment by Bosch-0** [comment]
I have similar sentiment to @sbddesign and @GBKS. I also think that the way this is being conducted that it could be formed into a great case study on the UX around merchants. We don't have the section live atm but a 'Case studies' section will be in the guide once we have some content to go into it (currently have none).

**Comment by GBKS** [comment]
@beanandcheeseburrito will you push more updates to this PR?

**Comment by GBKS** [comment]
Alright, I will close this PR if there are no updates by next Friday, July 15. Please reply if you think that is the wrong action to take.

**Pull request closed without merging**
