### PR TITLE
Added BOLTs to glossary

### PR DESCRIPTION
**Pull request by sbddesign**
⚡️ [See Deploy Preview](https://deploy-preview-496--sad-borg-390916.netlify.app/guide/glossary/#bolt---basis-of-lightning-technology)

I added BOLTs to the glossary.

I don't feel the need to list out various BOLTs in the same way that we list out various BIPs in the glossary. The reason is because the BOLTs don't always translate into "features" in quite the same way that BIPs do. For example, there is a BOLT for lightning messaging, a BOLT for gossip protocol, a BOLT for DNS bootstrapping -- all very important stuff, but I do not view these as discrete features that are directly relevant to designers.

### CODE REVIEW

**Comment by Bosch-0** [comment]
fyi I've got a WIP technology standards page that will eventually have designer relevant BIPs / BOLTs listed: https://github.com/BitcoinDesign/Guide/issues/291. When This is live I will move the BIPs listed in the glossary and just have a generic BIPs entry (similar to what you have done here with the generic BOLTs entry) that links to the standards page. Will link this BOLT entry to the standards page also once it's live.

**Review by Bosch-0 — APPROVED** [review]
LGTM

**Review by GBKS — APPROVED** [review]
Good addition.

**Review by johnsBeharry — APPROVED** [review]
LGTM

**Pull request merged**
