### PR TITLE
Replaces the blockchain.com screens with Muun screens

### PR DESCRIPTION
**Pull request by GBKS**
This is on the Common User Flows page. Addresses #266 .

@Bosch-0 added the Muun screens here. Let me know how that looks to you.

[Preview](https://deploy-preview-269--sad-borg-390916.netlify.app/guide/getting-started/common-user-flows/#software-onboarding)

### CODE REVIEW

**Review by pavlenex — APPROVED** [review]
LGTM

**Review by johnsBeharry — APPROVED** [review]
Is that a valid recovery key?

LGTM nonetheless.

**Comment by Bosch-0** [comment]
tACK from me, look good! Much cleaner using the image slide gallery :)

**Comment by GBKS** [comment]
It is a valid recovery key from a wallet I do not use. Deleted it and created a new one after taking screenshots.

**Review by Bosch-0 — DISMISSED** [review]

**Comment by GBKS** [comment]
One more approval, please. Had to resolve a conflict.

**Review by Bosch-0 — APPROVED** [review]

**Review by pavlenex — APPROVED** [review]

**Pull request merged**
