### PR TITLE
Move "Hiding sensitive info" content

### PR DESCRIPTION
**Pull request by GBKS**
Moves [Hiding sensitive info](https://bitcoin.design/guide/daily-spending-wallet/security/#hiding-sensitive-information) content from the [Security](https://bitcoin.design/guide/daily-spending-wallet/security/) page to the [Privacy](https://bitcoin.design/guide/daily-spending-wallet/privacy/) page.

The Privacy page does not flow particularly well now and needs further revision. Leaving this up to a separate PR in order to not overload this one.

🐛[Inspect the preview](https://deploy-preview-801--sad-borg-390916.netlify.app/guide/daily-spending-wallet/privacy/#hiding-sensitive-information)🐌

### CODE REVIEW

**Review by sbddesign — APPROVED** [review]
LGTM.
I think it works on Security or Privacy page. I don't have strong opinions about which. What doesn't flow right about it?

**Comment by GBKS** [comment]
> What doesn't flow right about it?

The page intro talks about network-level privacy, which we could broaden a bit. After this PR, the top half of the page is fairly text heavy with a few more abstract illustrations, while the bottom is more precise about specific UX techniques.

We should also decide how much of the on-chain content we want to keep (like the part about CoinJoins).

**Review by Bosch-0 — APPROVED** [review]
LGTM

**Comment by Bosch-0** [comment]
I agree, this page definitely needs a revision / more visuals. I'd remove the on-chain stuff we can go into that in the savings wallet reference design when we get there.

**Pull request merged**
