### PR TITLE
Private key management - Remove Key sharing / threshold signatures scheme

### PR DESCRIPTION
**Pull request by danielnordh**
As discussed in #313 we no longer want to promote or include this scheme.

This PR removes the page, any links to it and mentions of the scheme, any images used and updates an illustration to remove the scheme.

### CODE REVIEW

**Comment by Bosch-0** [comment]
For another PR, but relevant to this, we should add non-recommended schemes in the overview PKM page and link to external sources. This as well as WIF backups are things we can have there.

**Review by Bosch-0 — APPROVED** [review]
LGTM!

**Review by pavlenex — APPROVED** [review]

**Review by GBKS — CHANGES_REQUESTED** [review]
I think something went wrong as a few images were deleted from other pages that still use them. There are also 2 `.icloud` files that were committed. Could you please double-check?

**Comment by danielnordh** [comment]
Thanks for spotting that @GBKS. (Have now turned off the iCloud optimization that was messing with the folder content).
Reverted and applied the changes without the mistakes.

**Review by GBKS — CHANGES_REQUESTED** [review]
Could you please also delete the unused `wallet-recovery.md` file?

**Comment by danielnordh** [comment]
That is completely unrelated to this PR. But sure.

**Review by GBKS — APPROVED** [review]
Thanks for accommodating my last request. Let's get this merged.

**Pull request merged**
