### PR TITLE
Update - Add mobile friendly versions of spectrum and flow chart (Private key chapter)

### PR DESCRIPTION
**Pull request by danielnordh**
These were lacking mobile versions.
Also updated desktop versions to correct sizes.

### CODE REVIEW

**Review by GBKS — DISMISSED** [review]
tACK

**Comment by pavlenex** [comment]
We probably should add the ability to zoom in or open an image in the lightbox, graphics with lots of text are a bit hard to read.
Looks like a resolution/compression issue to me.

Screenshot from 2021-01-24 13-23-37

**Comment by pavlenex** [comment]
@GBKS I use [this](https://www.benq.com/en-ap/monitor/stylish/gw2270/specifications.html) one as my desktop.

**Comment by danielnordh** [comment]
Have updated non-mobile to full width for readability (this is the current state pre-merge, only difference is that it used to have a border).

**Review by GBKS — APPROVED** [review]

**Pull request merged**
