### PR TITLE
Adding image optimization plugin

### PR DESCRIPTION
**Pull request by GBKS**
Make sure to run "bundle install" before running the site. It will automatically start to optimize all images in the repo once you do.

The first commit does not include the optimized images. Want to make sure this works for everyone else first.

### CODE REVIEW

**Comment by pavlenex** [comment]
tACK on MacOS. From 55MB image folder compressed to 12.2MB.

I couldn't test it on Windows though, it seems it's a problem in my local setup that I need to figure out.

Tests are most likely failing due to the time it takes to run this on the initial setup as @GBKS explained.

**Review by pavlenex — APPROVED** [review]

**Comment by johnsBeharry** [comment]
The netlify build fails because it takes too long to compress then times out.

**Comment by GBKS** [comment]
@johnsBeharry yessir. That will be fine once we commit compressed images (and Netlify doesn't have to do that with every build). But before we commit them, I'd like for someone to test whether this plugin works for them as well and doesn't brick anyones local dev setup. @pavlenex has had some issues, which may have been particular to this computer.

**Comment by ConorOkus** [comment]
tACk on MacOS.

Would be nice if also output the compression stats in the command line as well

**Review by ConorOkus — APPROVED** [review]

**Comment by pavlenex** [comment]
I am not used to being the only guy with Windows, usually I am the MacOS guy! 😄 

Anyway, I run another test, this time I applied the fix described [here ](https://www.youtube.com/watch?v=eqFU0qEwDmo) and I was able to build and preview it, but my local folder still doesn't show compression. On MacOS I've tested and it works.

**Comment by GBKS** [comment]
I ran the script to optimize images and reviewed them afterwards. Should be good to merge this now. If anything got messed up, I still have a copy of the uncompressed images.

**Pull request merged**
