### PR TITLE
Letting the image compression script run

### PR DESCRIPTION
**Pull request by GBKS**
Various images have been committed without compression. This compresses them.

### CODE REVIEW

**Comment by pavlenex** [comment]
Wait so we actually have to commit those? This should be mentioned somewhere, I thought it was my IDE bugging and that script will compress them later on once it's pushed.

**Comment by GBKS** [comment]
@pavlenex yep, they have to be committed. Remember how the first PR for the image compression script timed out because it took so long? That's because it had to compress all images in the repo.

I added a note that [bottom of the new illustration guidelines page](https://deploy-preview-113--sad-borg-390916.netlify.app/guide/contribute/illustration-guidelines/#file-size-optimization), but probably need to mark that a more precise. Think we also need a video for this whole thing.

**Comment by pavlenex** [comment]
I think once we have a specific "How to submit" or commit page which outlines the GitHub process (I'd like work on this) it can be added there as well? Glad to know I no longer have to discard these changes in IDE, silly me :smile:

**Comment by johnsBeharry** [comment]
Every time I switch a branch i'm having conflicts with `_compress_images_cache.yml` as do you with this PR.

I really dislike this method of compression we use. I'm starting to think having the PR compression bot isn't such a bad idea.

**Comment by GBKS** [comment]
@johnsBeharry this wouldn't be an issue if people compressed their images before committing, meaning they need to run the site locally. Question is whether this is too much to ask? Maybe. Daniel, for example, said that he doesn't want to bother with running the site locally and instead pushes his changes and reviews them on the preview links. Sounds a lot more tedious to me personally, but that's his preferred workflow.

Alternatively, we can make image compression a separate script that we either run once a week, or ask people to run before merging PRs. That way it doesn't interfere with the workflow when you switch back and forth between various branches (which I've also found bothersome).

**Comment by johnsBeharry** [comment]
Ye it may be down to going between branches that are a bit older than those which have compression then.

I've only recently gotten the site back up and running locally myself, and I have to often delete the `Gemfile.lock` and bundle install. But I think that's down to a user error.

**Review by pavlenex — APPROVED** [review]

**Review by johnsBeharry — APPROVED** [review]

**Pull request merged**
