### PR TITLE
Usability and footer tweaks based on feedback

### PR DESCRIPTION
**Pull request by GBKS**
This addresses the super small easy-to-implement site [feedback we got from Sven](https://discourse.opensourcedesign.net/t/new-contribute-join-page-in-the-bitcoin-design-community/3769/2) in the Open Source Design forum.

- Adding Nostr and BitcoinTV logos to the footer
- Add a hover tip to the footer logo and the header search icon
- Active and visited states for footer links

Since Nostr is not a single service, the link goes to Nosta, which is a service meant for showing Nostr profiles. I am also the creator of Nosta, so am I self-serving by doing this? Let me know what you think, we can change the link elsewhere.

Going to keep it as a draft since I want to look over the feedback again and make sure I captured everything that needs to go in this PR.

🩴[Check the preview](https://deploy-preview-1085--bitcoin-design-site.netlify.app)👠

### CODE REVIEW

**Comment by mouxdesign** [comment]
LGTM. using Nosta seems perfectly fine.

Footer links: I see that when I hover over the link the copy changes from black to orange. Upon click and returning to the page the copy remains black. Was there another hover (visited) state planned or perhaps it is not showing up on my end.

**Comment by rabbitholiness** [comment]
Looks good to me with one exception: I see the active state (orange) in the footer links, but not the visited state (like Mo mentioned as well).

Linking to Nosta is fine, I think.

**Comment by GBKS** [comment]
Thanks for the feedback. Can you please check again? I made a few tweaks.

**Comment by mouxdesign** [comment]
Works perfect! The visited links in the footer are now showing up as grey text, 
Screenshot 2024-06-21 122006

**Review by mouxdesign — APPROVED** [review]

**Pull request merged**
