### PR TITLE
Search improvement

### LINKED ISSUE #1032: Update the site search
While discussing search with the Wallet Scrutiny team, I saw that the [JS library](https://lunrjs.com) we use in our site/guide is outdated. We use 0.7.1, the latest version is 2.3.9. This should give us new capabilities like fuzzy matching. So if someone accidentally types "bitgoin", it will show results for "bitcoin" (the live site does not do this right now). A couple of other ideas:

- Lunr give us a score for each result. Can we show a small visual indicator how confident we are in the match? This is slightly tricky because the [score](https://en.wikipedia.org/wiki/Okapi_BM25) is not normalized across queries (one search might produce a range of 3-12, another one 1-7). Helps people decide which result to click on.
- When nothing was found, offer to make the search more fuzzy.
- When too many results, offer using [boosts](https://lunrjs.com/guides/searching.html#boosts) (weigh one term more than another) or [term presence modifiers](https://lunrjs.com/guides/searching.html#term-presence) (some terms have to be there, others cannot be there).
- Add some custom goofy results just for fun - easter eggs.

This probably needs some testing of different search intents and terms to narrow in on what produces the "right" results. So a good idea might be a draft PR for hands-on testing changes, and a design mock-up for exploring visuals, and then merging the two.

### PR DESCRIPTION
**Pull request by GBKS**
This is a bigger update to the search functionality on the site.

I updated the [LunrJS](http://lunrjs.com) library, which powers our search. The latest version has some extra features like fuzzy search and term presence. This is now enabled and highlighted to users on the search page via an expandable "Search tips" section. For simple single-term searches, the site uses a slightly fuzzy search. So if you type "bech31", it will also find "bech32". Or if you type "wxllet", it will also find "wallet". Helps with those small typos or easy-to-misspell technical terms.

I removed our SEO placeholder pages from the search index. These are currently causing search results that read "..." on the site. Not pretty. The search page is also removed from search results. Also, the search input field now has a placeholder and I fixed a technical issue with a misspelling. 

Search results now also have a small dot next to them to indicate the quality/confidence of the result. Green is a good match, grey is just an OK match. Colors can range in between those two based on the scores.

The search tips are a little hidden, just being visible on the search page. Would be nice to include them somehow in the search modal as well, without cluttering things up.

Probably good to test this thoroughly before finalizing. Would be great if you could help test some searches, especially ones you have previously used and maybe not found good results for.

Some preview links:
- A [page with no results](https://deploy-preview-1034--bitcoin-design-site.netlify.app/search?query=nonsense), showing how the search tips are readily available
- "wollet" [results](https://deploy-preview-1034--bitcoin-design-site.netlify.app/search?query=wollet) (compare to the [live site](https://bitcoin.design/search.html?query=wollet))
- "wallet" [results](https://deploy-preview-1034--bitcoin-design-site.netlify.app/search?query=wallet) no longer show the "..." entries (compare to the [live site](https://bitcoin.design/search.html?query=wallet))
- "backup -cloud" [results](https://deploy-preview-1034--bitcoin-design-site.netlify.app/search?query=backup+-cloud) no longer include the term "cloud" (compare to [live site](https://bitcoin.design/search.html?query=backup+-cloud))

Closes #1032

### CODE REVIEW

**Review by danielnordh — APPROVED** [review]
Tested and gives better results.
LGTM

**Comment by rabbitholiness** [comment]
I tested the use cases that you mention above. Works as promised 💪.

I really like the search tips. Agree that it could be nice in the modal. On the results page, they are a bit hidden at the bottom of the list. Maybe it's worth trying to place it somewhere underneath the search box.

The dots are a nice indicator if one knows what they represent. Personally, I wouldn't have guessed what they mean. 

Not sure this is relevant or anything can/should be done about it, but it seems that with very short search terms I get a lot of unrelated results, where the live site doesn't. 
I tried searching for the word "scam". On the live site this yields no results. In the preview I get [a lot of results](https://deploy-preview-1034--bitcoin-design-site.netlify.app/search?query=scam) that are not relevant. When I clicked through to some of the found pages, I tried the browser search to see what triggered the results. No three letter combination yielded results (e.g. sca or cam). When I searched for two characters (sc, ca, am,...) I got a lot of results . This is probably due to the fact that it is a very short search term and I'm not sure whether this needs to be addressed, but I just wanted to mention it.

**Review by sbddesign — APPROVED** [review]
# 🔎

**Comment by GBKS** [comment]
Thanks for the reviews and feedback. I just fixed the merge conflict and made a small tweak to add a tool tip to the match quality indicator dots (hover one and see "Great match", "Good match" or "OK match").

@rabbitholiness good point about short results. That is a side effect of making simple searches fuzzy. The same logic that brings up find "bech32" when you types "bech31", also creates false positives. This is ideally where the match quality indicator helps you identify what results are worth looking at.

Interesting that you searched for the word `scam`. Feels like this could be an easter egg term where we show you [an appropriate GIF](https://giphy.com/gifs/Murdoch-Mysteries-murdoch-mysteries-shanice-banton-Cx39vxBSBPt6imKpNz) instead of actual results.

Generally, ready for the next round of reviews. Thank you in advance.

**Review by sbddesign — CHANGES_REQUESTED** [review]
I think I found a weird bug here:

1. Click on search
2. Fill search input with a single word string with no whitespace, e.g. `wallet`
3. When the dropdown populates with search results, do NOT hit enter. Instead, click the "See X Results" button.

image

4. Notice that the search results have a tilde and 1 appended, e.g. `wallet~1`

image

As far as I can tell, [with tilde](https://deploy-preview-1034--bitcoin-design-site.netlify.app/search?query=wallet~1) and [without tilde](https://deploy-preview-1034--bitcoin-design-site.netlify.app/search?query=wallet) seem to produce the same search results. It just looks kind of tacky.

**Review by sbddesign — APPROVED** [review]
# 🤙

**Pull request merged**
