### PR TITLE
Added Briding Bitcoin theme configuration and images

### PR DESCRIPTION
**Pull request by GBKS**
For Alexas home page header design in issue #45 .

### CODE REVIEW

**Review by ConorOkus — APPROVED** [review]
Very cool 👍

**Comment by GBKS** [comment]
@Christoph Ono I have not taken out the blank theme template yet. Should we keep it in until we have a few more themes? Or kick it out and let Alexa dominate?

**Comment by ConorOkus** [comment]
I actually like the minimalism of it, so I'm happy to leave it in to be fair. No strong opinions either way though

**Comment by danielnordh** [comment]
I would keep the blank one.

**Pull request merged**
