### PR TITLE
Adds a "Feedback & questions" button to guide pages

### LINKED ISSUE #889: Add more interaction/share options to each page
We've discussed a few times that it's not obvious how to ask a question about a page, or propose a change. As shown in the mock-up, we could add options to the bottom of each page that lets the user take various questions. The design is pretty non-intrusive. 

image

If we implement something like this, we'd have to keep an eye out if more people do end up asking questions in Slack or opening up discussions on Github, etc.

What options should should we provide?

### PR DESCRIPTION
**Pull request by GBKS**
See #889 for details. Need to cross-browser test this with the preview URL. If you want to test, pull up the link below and find the `Feedback & questions?` link in between the pagination to the next and previous pages. Click it to show/hide options, and see if they take you to the right places. Also happy to hear recommendations on whether those links are good, or we should link elsewhere.

🍢[Check the preview](https://deploy-preview-899--bitcoin-design-site.netlify.app/guide/getting-started/introduction/#hardware-categories)🍡

Closes #889

### CODE REVIEW

**Comment by pavlenex** [comment]
Tested and it looks good to me, but my main concern is that it's not really that visible, thoughts on making it a bit more prominent? A simple thing such as color change can be helpful, or making it a CTA button.

**Review by pavlenex — APPROVED** [review]
Sure I don't object to that, let's give it a try!

**Comment by mouxdesign** [comment]
I like this new addition very much, how do you guys feel about maybe adding in the link on the how to propose a change? There are quite a few UX designers that also use the guide. So Github is pretty new to them, this [one](https://deploy-preview-899--bitcoin-design-site.netlify.app/guide/contribute/propose-a-change/) is very good.

**Comment by mouxdesign** [comment]
Also really like how this is on the footer of the GetAlby newsletter, its quite prominent and brings the eye to the text with the separation of color.
 
The text "need help" might also be nice to add, letting the user know that if they didn't find an answer to their question they are also most welcome to ask within the community. 
 
Alby

**Pull request merged**
