### PR TITLE
Glossary - Add 'passphrase'

### PR DESCRIPTION
**Pull request by danielnordh**
Adds 'pass phrase' to the glossary

### CODE REVIEW

**Review by pavlenex — CHANGES_REQUESTED** [review]
pass phrase  or passphrase?

 I've only see the latter being used. It's also defined as passphrase in the BIP39 proposal so I suggest we stick with that.

https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki

**Comment by danielnordh** [comment]
> pass phrase or passphrase?
> 
> I've only see the latter being used. It's also defined as passphrase in the BIP39 proposal so I suggest we stick with that.
> 
> https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki

OK, can change. I used pass-phrase on the backups page, but was going to align with 'recovery phrase', where we neither use a hyphen nor a single word.

**Comment by danielnordh** [comment]
> pass phrase or passphrase?
> 
> I've only see the latter being used. It's also defined as passphrase in the BIP39 proposal so I suggest we stick with that.
> 
> https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki

Resolved in a2eadcc (also updated on backups page)

**Review by pavlenex — APPROVED** [review]
Thanks for quickly updating these, LGTM.

**Pull request merged**
