### PR TITLE
Update content-guidelines.md

### PR DESCRIPTION
**Pull request by sqcken**
Ken edits to content-guidelines.

### CODE REVIEW

**Comment by johnsBeharry** [comment]
hey @sqcken thanks for the contribution! just to get some context around the changes you've done, could you explain the problem you're addressing and reason for your solution for this PR?

Here's an example outline:

```
### Problem
- State the problem/s being addressed
### Solution
- What is your proposed the solution
### Result
- How was it finally implemented?
- What parts are you requesting to be reviewed?
- How is it to be used?
```

**Comment by GBKS** [comment]
Thanks for the edits. This new version definitely reads better. As Johns said, it would be helpful if you could add the context for the changes and explain any ideas, approaches, criticism, etc so everyone can better understand how you came up with the edits.

**Comment by sqcken** [comment]
Hey guys. Happy to. I'm still super new to GitHub so I hope I'm putting this in the right place.

### Problem
The content-guidelines that I saw could have been written more clearly and concisely. They weren't as easy to grasp for a non-English speaker or first-time bitcoin designer as I would have liked them to be. There were also a number of small errors that needed cleaning up.

### Solution
Clearer, more direct sentences with an overall focus on concision. Clean up typos and other grammatical errors. More sentences opening on verbs to convey action. 

### Result
- How was it finally implemented?
As noted above. It wasn't a long edit but a necessary one. 

- What parts are you requesting to be reviewed?
All of it. At some point it might even be beneficial for me take a second when the guide is closer to finished.

- How is it to be used?
Ask Christoph. I imagine it will eventually be dropped into the guide.

**Comment by GBKS** [comment]
Thanks for the background. Right on with the focus on non-English speakers and first-time designers.

**Pull request merged**
