### PR TITLE
Added New recovery header images

### PR DESCRIPTION
**Pull request by pragya1976**
#914 

Illustration source: [Figma link](https://www.figma.com/file/T5bOl3TW1MxNHXqEx4H0PX/recovery-header?node-id=0%3A1&t=KLd988t7N9kKhCRH-1)

The following illustrations for Recovery page header have been made by getting inspiration from the rough sketch provided in the issue itself. Here is that rough sketch for reference:

rough sketch

### CODE REVIEW

**Review by GBKS — CHANGES_REQUESTED** [review]
Thank you for submitting these images. I have a bit of feedback to get this over the line.

- Please also create a "preview" image that is 1200x630px. This will be used as a thumbnail when sharing the page on social media. The current preview image is `restoring-a-wallet-preview.png`, if that helps
- You added the images, but they are not being used yet, because the page markdown still references the old images. Are you comfortable updating these images references?

Let me know if you'd like help with anything.

**Comment by pragya1976** [comment]
Thanks for the feedback .Will do the desired changes

**Comment by pragya1976** [comment]
The required changes have been made. Please review

**Comment by pragya1976** [comment]
@GBKS changes have been made .Can you please review them

**Comment by GBKS** [comment]
Thanks for the update. Just one more small thing. Since you are replacing old images with new ones that have different file names, could you please delete the old ones that are not used anymore? It helps keep our repository organized.

**Comment by pragya1976** [comment]
ok sure

**Review by sbddesign — CHANGES_REQUESTED** [review]
Looking very good! One small thing. Could you add a link to your figma file to the source code? Look in the file for this:

```
<!--

Design source for the header image:
https://www.figma.com/file/qr4P17z6WSPADm6oW0cKw2/?node-id=0%3A1
```

And just replace the figma link with the link to your figma file. Same with #1004, actually.

**Comment by sbddesign** [comment]
Also, same comment I left on your other PR. I do not see any entries in `_compress_images_cashe.yml`, which means the images have not been compressed for the word. You can do this by running the site site locally using `bundle exec jekyll serve` or `docker-compose up`. Alternatively, I can handle this for you if you and push it to your branch if you like.

**Comment by pragya1976** [comment]
Thanks for the feedback . I will do the required changes .

**Comment by pragya1976** [comment]
@sbddesign I have added the figma links in the source code but I am unable to run the site locally. Please can you help me by 
creating entries of these images `_compress_images_cashe.yml`.

**Comment by pragya1976** [comment]
@yashrajd I am unable to setup docker on my laptop.

**Comment by yashrajd** [comment]
Are you not able to install Docker Desktop on your machine? What's the error? Posting specifics will help people troubleshoot if we can.

**Comment by GBKS** [comment]
@pragya1976, if you are having a lot of problems [setting it up](https://github.com/BitcoinDesign/Guide#how-to-build-and-run-the-site-locally), please share as it's good for us to know about. 

I know this can be a big pain sometimes. If you don't want to deal with it for this PR, @sbddesign offered to do it for you, and I can do that as well. Just let us know.

**Comment by pragya1976** [comment]
@GBKS I am facing problem in setting it up.

**Review by GBKS — DISMISSED** [review]
ACK. @pragya1976 I fixed the image issue for you. Should be good to go now.

Heads up that we cannot help you set up your local dev environment if you don't tell us what the specific problems are you are encountering.

@sbddesign could you please update your review?

**Comment by sbddesign** [comment]
The only issue I see is that the preview image has not been compressed. (An oversight because it uses the same filename as the original). I think we should fix that in a separate PR, I'm finding it a little tricky to do that on Pragya's master branch.

**Review by sbddesign — APPROVED** [review]
Excellent!

**Pull request merged**
