### PR TITLE
Updates the site logo to the seal

### PR DESCRIPTION
**Pull request by GBKS**
Changes the favicon and logos used in the mobile header, home page banner, and site footer.

🌅[Preview](https://deploy-preview-556--sad-borg-390916.netlify.app)🎇

The generic outline Bitcoin symbol was replaced with the community seal. I've run this design change past the community on Slack and several people individually. So far everyone seems to agree that this is a good direction, now let's see how we like it in the site itself.

[Figma file for the new logo](https://www.figma.com/file/x0F4rdZbPykk35mLrZLfwo/Bitcoin-Design-Community-branding?node-id=6%3A369). I also added this as a link on the [Design resources](https://deploy-preview-556--sad-borg-390916.netlify.app/guide/designing-products/design-resources/) page.

Thoughts
- The seal in the header on mobile looks really skinny. Do we want to keep this?
- Applying the theme in the home page banner on desktop has slightly changed due to the new seal being more dependent on lines for readability. Any changes there?
- The [link preview image](https://bitcoin.design/assets/images/bitcoin-design-preview.jpg) for the home page still uses the old logo. Should we change it?

This is now ready for review. Thanks in advance.

### CODE REVIEW

**Comment by pavlenex** [comment]
Cool one thing to note about the new logo is that it doesn't look great in the github's dark mode.
Screenshot 2021-11-09 at 13 59 42

**Comment by GBKS** [comment]
@pavlenex excellent catch. Going to revise this pronto. At the end of this, I want to have a Figma community file and a section on the site with good ready-to-use logos for everyone to use.

**Comment by GBKS** [comment]
@pavlenex Github logo should be fixed now (unless caching messes with things).

**Comment by pavlenex** [comment]
Way better now, thanks for fixing it 🎉 
Screenshot 2021-11-09 at 16 51 25

**Comment by johnsBeharry** [comment]
What about the preview image? Would this also need updating?

**Comment by GBKS** [comment]
@johnsBeharry how about this?

bitcoin-design-preview

**Comment by johnsBeharry** [comment]
i'm digging it lots @GBKS

**Comment by GBKS** [comment]
@johnsBeharry funny you ask, that's how I had it first (blue in the top left), felt a bit cold though, so I went with the warmer yellow.

**Review by Bosch-0 — APPROVED** [review]
LGTM, tested on iPad and mobile too all looked well to me :)

**Review by Bosch-0 — APPROVED** [review]

**Comment by danielnordh** [comment]
LGTM

**Review by danielnordh — APPROVED** [review]

**Pull request merged**
