### PR TITLE
Minor screen revision for `Daily spending wallet` > `Automatic cloud backup`

### PR DESCRIPTION
**Pull request by GBKS**
This is part of issue #800. To create the prototype, we need all screens to be consistent, and have them in a [single Figma file](https://www.figma.com/file/lf2Xyw2I2OXPsHiFQVQdiG/Daily-spending-wallet-prototype?node-id=4152%3A306968&t=boEAgdyqfi39SBoF-1). This update includes minor consistency tweaks to images, added modal images, and an updated image source link in the markdown file for the [Automatic cloud backup](https://bitcoin.design/guide/daily-spending-wallet/backup-and-recovery/cloud-backup/) page.

🤦🏽[Check the preview](https://deploy-preview-947--bitcoin-design-site.netlify.app/guide/daily-spending-wallet/backup-and-recovery/cloud-backup/)🙋🏼

### CODE REVIEW

**Review by pavlenex — COMMENTED** [review]
LGTM, but what is `Russian glowcap`?

**Comment by GBKS** [comment]
That's a question for @sbddesign .

**Comment by sbddesign** [comment]
@pavlenex I needed a placeholder name for an imaginary lightning wallet service provider or cloud backup option. Just stole a word from an old videogame. Nobody ever questioned it, so it got merged in when I updated all the Backup sections earlier in the year.

**Review by sbddesign — COMMENTED** [review]
image

I hate to bikeshed, but this typography just looks nasty. Center-alignment is fine for smaller tidbits of text, but I think it starts to become a little awkward to read a full paragraph of text  in center alignment.

Is this going to be some kind of rule with the Bitcoin UI Kit, that all text must be center aligned?

**Review by sbddesign — APPROVED** [review]
🦓

**Comment by GBKS** [comment]
@sbddesign I know what you mean, but it's also really weird when 99% of text is centered and just the occasional one is left-aligned. I think the solution here is to split it up into two paragraphs to avoid the effect you're pointing out.

**Pull request merged**
