### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by paulosacramento**
Adding the term 'block reward' to the glossary, as suggest by @johnsBeharry here: https://github.com/BitcoinDesign/Guide/issues/511

### CODE REVIEW

**Comment by GBKS** [comment]
Good addition. We should link to this entry from the Tech Primer page, the block reward is mentioned [here](https://bitcoin.design/guide/getting-started/technology-primer/#how-is-the-blockchain-secured).

**Review by paulosacramento — COMMENTED** [review]
https://github.com/BitcoinDesign/Guide/pull/566#issuecomment-972671920

**Review by Bosch-0 — DISMISSED** [review]

**Comment by pavlenex** [comment]
@paulosacramento I think @GBKS meant that you should link from the Tech Primer page to this page, not vice-versa.

So just add a link to this page in tech primer.
Screenshot 2021-11-18 at 13 24 46

**Comment by paulosacramento** [comment]
This makes sense. Thanks!

**Comment by paulosacramento** [comment]
Oh, before doing it I must wait before the new addition to the glossary has been reviewed and approved.

**Comment by pavlenex** [comment]
@paulosacramento you can do it in a same pull request.

**Comment by pavlenex** [comment]
@paulosacramento you need to push the latest change to this branch, LMK if you need any help with that, as your latest tech-primer pushed on your fork, but the wrong branch. You should push it to `patch-12` not `patch-14`

**Review by pavlenex — APPROVED** [review]

**Pull request merged**
