### PR TITLE
WIP: Glossary refactor to use jekyll collections

### LINKED ISSUE #281: Extract address content from Glossary into a sub-page
[The information](https://bitcoin.design/guide/glossary/#address) is good, but too much for the glossary, which is meant for short explanations. We could put this new "Addresses" page under foundations, or under glossary. Glossary doesn't have sub-pages at the moment, but this is something we've discussed before.

bitcoin design_guide_glossary_ (5)

### PR DESCRIPTION
**Pull request by johnsBeharry**
This PR transforms the glossary page into a jekyll collection.

NOTE: All glossary terms have their own page, but are not linked from the glossary page until a summary is written. Not all terms in the glossary are currently setup to be linked (since the content is already shown in full on the current `/guide/glossary` page).

**Progress**
- All terms are to be their own markdown documents in `/_glossary`
- Terms with a summary property set in frontmatter are automatically linked from the glossary page.
- Anchor links are shorter, they represent the file name instead of the title
- Permalinks do not need to be set because it

**Problems**
- A new glossary layout had to be created to show the page title and glossary table of contents
- The default layout had to be adjusted as the sidebar was dependent on the permalink property, the glossary collection is setup to use the file names instead of permalinks.

**Plans**
- Ensure anchor links to glossary throughout the site are not broken
- Update term content in `_glossary` as it is currently outdated

Closes #281 and #282

### CODE REVIEW

**Comment by johnsBeharry** [comment]
Seeking a concept and technical ACK, NOT a content review. Are you happy with managing the glossary content in this way?

@Bosch-0 @GBKS @pavlenex @ConorOkus

**Comment by GBKS** [comment]
I like the big idea of splitting the glossary into individual files, one for each term. It's currently tedious to manage and review changes. So ACK on the concept.

I am torn on one detail of the implementation, which is that if a term has both a summary on the glossary page, and a dedicated sub-page, both of those pieces of content live in the same markdown file. The summary becomes a single frontmatter property, which doesn't allow for line breaks, bullet points, etc. This unnecessarily limits glossary entries. My recommendation would be to have one markdown file for whatever is shown on the glossary page, and create a new sub-page markdown file for a term if needed, which can use the identical markdown and writing process of all our other pages.

I also saw that `rake test` picks up the unlinked glossary HTML pages and throws a lot of errors for broken links. That's because those pages display content that is really only meant for the glossary main page, in which those links work. No idea if there's a way around it, if we go with this approach.

**Comment by Bosch-0** [comment]
Concept ACK

> My recommendation would be to have one markdown file for whatever is shown on the glossary page, and create a new sub-page markdown file for a term if needed, which can use the identical markdown and writing process of all our other pages.

I think this is a better way to go about it than includes for the same reasons Christoph outlined.

Visually it would be good to make it clearer that these large entries can be expanded upon.

**Comment by johnsBeharry** [comment]
@Bosch-0 @GBKS from what I'm getting it seems like this is a concept and technical NACK.

Based on that feedback I then propose a new PR with the following: 

- move existing glossary.md -> glossary/index.md
- create glossary/addresss.md
- create glossary/wallet.md

Would that be acceptable?

**Comment by ConorOkus** [comment]
Concept ACK & Technical NACK

**Comment by GBKS** [comment]
> My recommendation would be to have one markdown file for whatever is shown on the glossary page, and create a new sub-page markdown file for a term if needed, which can use the identical markdown and writing process of all our other pages.

Just to clarify, I meant one markdown file per glossary entry. Then all of those get combined to form the glossary page. And sub-pages are just regular old sub-pages.

**Comment by johnsBeharry** [comment]
> And sub-pages are just regular old sub-pages

seeing further clarification, would that result in two files for terms like addresses?

**Comment by GBKS** [comment]
Yessir. You would have `_glossary/address.md `for the short summary that get compiled into the main glossary page. And you'd have `guide/glossary/address.md` for the glossary sub-page that lays out address info in detail.

**Comment by johnsBeharry** [comment]
Superseded by #410

**Pull request closed without merging**
