### PR TITLE
Moved remaining case studies to top-level as reference designs

### PR DESCRIPTION
**Pull request by GBKS**
Addresses #716.

Only moved and updated markdown files here and avoided images to prevent the PR from getting huge and messy. Images can be moved in a separate PR.

One thing to note is that there is no "/reference-designs/" folder. We previously had these case studies in a sub-folder under "/case-studies", but now they are moved to the top-level - consistent with the already moved daily spending wallet. Nothing big, just wanted to highlight that.

Looking at the files changed here, it appears that Github thinks I re-wrote two pages when I only updated the nav order meta property at the top. No clue why it marked all the content as removed and new content added, despite it being the same. Anyone know why that might be?

### CODE REVIEW

**Review by Bosch-0 — APPROVED** [review]
LGTM, pretty straight forward PR!

**Comment by pavlenex** [comment]
> Looking at the files changed here, it appears that Github thinks I re-wrote two pages when I only updated the nav order meta property at the top. No clue why it marked all the content as removed and new content added, despite it being the same. Anyone know why that might be?

This happens when a file is renamed it thinks it's a new one.

@GBKS Not the point of the PR, but `Reference Design` doesn't exist as a nested section per se? Because I'm noticing it's not named like that in the sidebar, and we don't link to it from the `/guide` but we do link to it's `children`?

**Review by pavlenex — APPROVED** [review]
tACK

**Comment by GBKS** [comment]
@pavlenex here's one of the design concept to introduce a reference designs title in the sidebar nav that matches the new design of the guide landing page. Right now, there is no landing page for "Reference designs" and we may not even need one since the new landing page already highlights them well.

reference-designs-nav

Just a concept for now. How does that look to you?

**Comment by Bosch-0** [comment]
I'd give the reference designs lower opacity, not the sections. The sections are the important pieces of content and the lower opacity lowers them in the hierarchy of the menu

**Pull request merged**
