### PR TITLE
Revised images in the Usage Life Cycle page

### PR DESCRIPTION
**Pull request by GBKS**
During the visual review (#245), I noticed a few pages that are all black-and-white. Some user feedback has also come in that the black-and-white images look not complete. So I'm looking into adding a bit more color and visual expression, starting with this page.

Changes:
- Added coloring to match visual style Jessica introduced in her banner, see #289
- Switched to PNG for better compression
- Fixed duplicate image alt tag copy

Frame 88

### CODE REVIEW

**Review by pavlenex — APPROVED** [review]

**Review by pavlenex — APPROVED** [review]
tACK
@GBKS  Really nice and playful style, should we do this for other chapters where we have the same icons or?

**Review by johnsBeharry — APPROVED** [review]
Damn. Really really like this style.

Edit: Off we got conflicts again with `_compress_images_cache.yml`. Why is this happening so often now?

**Comment by GBKS** [comment]
@pavlenex I updated icons on other pages as well today, using different styles that match the visuals that were already used on those pages. I wouldn't press so hard on standardizing visual treatments. Even if we use different colors, drop-shadows, etc, there still is consistency in the icon shapes, image size, etc. It's that balance of having some foundational things consistent, and opening up other areas to be more playful.

**Review by johnsBeharry — APPROVED** [review]
Looks good to go.

**Pull request merged**
