### PR TITLE
Style improvements to tables and footnotes and some other updates

### PR DESCRIPTION
**Pull request by johnsBeharry**
### Problem
1. "Uncaught TypeError: Cannot read property 'addEventListener' of null"
2. table displays a bit weird see below 
3. footnote looks like dangling links or part of the content

#### Table has weird borders
Screenshot 2020-12-11 at 00 17 10

### Solution
- fix(theme): check if banner exists before event listener
- style(article): distinguish footnote from content
- style: stretch and reduce styling of table

#### Table
Screenshot 2020-12-11 at 00 12 27

#### Footnote
Screenshot 2020-12-11 at 00 11 52

Screenshot 2020-12-11 at 00 13 33

### CODE REVIEW

**Comment by GBKS** [comment]
I like the changes. General question: do we want to tackle design/style changes first in Figma before applying them to code?

I have a bunch of styles already in Figma [here](https://www.figma.com/file/K5ahSqVzoMVBuhT5hAVRJr/Bitcoin-Designers-Website?node-id=24%3A18) with some of them in component form also in Figma [here](https://www.figma.com/file/K5ahSqVzoMVBuhT5hAVRJr/Bitcoin-Designers-Website?node-id=446%3A2473).

**Comment by GBKS** [comment]
Alternatively, we can say that changes start either in code or design, but we need to make sure that both places mirror each other...

**Comment by johnsBeharry** [comment]
> Alternatively, we can say that changes start either in code or design, but we need to make sure that both places mirror each other...

Agreed, its a bit difficult to find these resources now though - I knew you must have had something for the page designs but all I found was [this one](https://www.figma.com/file/IGTf3AvpStKyzbQZWmH5Sz/SquareCrypto-%2F-BitcoinDesign?node-id=0%3A1&viewport=264%2C20%2C0.13998600840568542) before I started this update.

Shall we start using the BitcoinDesign figma team - even if its just 3 editors at a time at least we can have a central place to look. Either that or we document the various files on contributing.md

**Comment by GBKS** [comment]
We can also link to that Figma file directly at the top of the "style" page, along with a short introduction. Seems like the right place.

For other Figma files, I've added source links at the top of the markdown pages they are used in, in an "Editor's notes" comment.

Yeah, let's talk through how we could use the team account. I haven't looked closely what the benefits and disadvantages are beyond the editor limit.

**Pull request merged**
