### PR TITLE
Added Bitcoin Core to contribute page.

### PR DESCRIPTION
**Pull request by Bosch-0**
Added Bitcoin Core to the contribute page.

### CODE REVIEW

**Review by johnsBeharry — APPROVED** [review]

**Comment by GBKS** [comment]
Just FYI, this is a placeholder page that Pedro briefly threw together early on. It's not clear whether we need this page or what the content should be. But maybe now is the right time to talk about it?

**Comment by Bosch-0** [comment]
Having some information about contributing to various open source Bitcoin projects somewhere on the site would be useful. Having a separate menu item called 'Contribute' for this is probably not the best way to go about it. Including this as part of the projects page would be more suitable. If we opt to have a 'Contribute' page it should solely for details on contributing to Bitcoin Design site/guide.

Here is a quick mockup of an idea for the Projects page with a contribute option. Expanding the project can give more specific details like project needs, contact details, resources etc. It could also be useful to have filters for this page as the list grows.

**Comment by GBKS** [comment]
@Bosch-0 I like the proposal. Do we have any other projects that should go on this page?

**Comment by pavlenex** [comment]
If you'd like to include BTCPay Server at some point, we do have quite detailed (but still WIP) guidelines on how to contribute which the link may point to https://docs.btcpayserver.org/Contribute/

**Comment by Bosch-0** [comment]
There is loads of great projects (enough for this page to get quite large so some filtering would be helpful). Though getting the page structure finalized before worrying about what content to include is more important.

**Comment by GBKS** [comment]
Do you mean projects that we recommend contributing to, or projects that community members are already actively participating on?

**Comment by Bosch-0** [comment]
Both? We could have the projects page split into two pages one for a general list of open source projects that designers can contribute to and one for BitcoinDesign specific projects (e.g. Johns or Jaamal's projects).

**Comment by GBKS** [comment]
ACK. How about we start with a Google Doc or Figma file and work out the copy for this page?

**Comment by Bosch-0** [comment]
Sounds good! Created a Figma file and send you an invite to edit: https://www.figma.com/file/qG1NCbVVaQDItmfXdY0oWN/Bitcoin-Design-Projects-Page?node-id=0%3A1

If anyone wants edit access comment below.

**Comment by johnsBeharry** [comment]
@Bosch-0 does this new design super seed this PR now? If it does then probably best to close this one off, otherwise I'll merge it in and we can continue the discussions for the updated page design on a new issue/PR.

**Review by johnsBeharry — APPROVED** [review]

**Comment by Bosch-0** [comment]
Yeah it does, I will open a new issue once some designs our laid out in that Figma file linked above.

**Pull request closed without merging**
