### PR TITLE
Fix various image-related minor issues on the coin selection page

### PR DESCRIPTION
**Pull request by GBKS**
Addresses parts of #360.

Move images to the correct folder (they were in the glossary before).
Add proper alt descriptions.

[Preview](https://deploy-preview-414--sad-borg-390916.netlify.app/guide/payments/send/coin-selection/)

@barefoot-88 could you please let me know where I can find the source for the page header image? The 2x version should be twice the size, and the 1x version 4x the size.

### CODE REVIEW

**Comment by barefoot-88** [comment]
Thanks @GBKS for pointing these out. Going to try and fix the issue now!

**Review by johnsBeharry — COMMENTED** [review]
All looks good on the technical side, I'm happy to see git mv used instead of delete and add (less space used). Only thing missing is the editor notes which I think should be included in this PR as this one already deals with images.

**Comment by johnsBeharry** [comment]
@barefoot-88 I've invited you to a figma file where we can put all the graphics for the payments section. Do you mind moving your illustrations over to there? I don't know if this may cause issues with any components being detached from the master one though since its using the bitcoin ui kit.

Thoughts on the source files only using frames and groups instead of components @GBKS?

**Review by pavlenex — APPROVED** [review]

**Comment by GBKS** [comment]
@johnsBeharry feel free to open another PR with editors notes and source files whenever. Whether components are used or not is up to you. Some designs lend themselves well for components, others don't.

**Pull request merged**
