### PR TITLE
Updating dependencies 

### PR DESCRIPTION
**Pull request by pavlenex**
While trying to build the website locally I encountered plenty of problems with Mac M1. While I described some of them on Slack, I finally managed to figure things out.

I've tested this with Ruby ` 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]`

This PR updates:
- listen (3.4.1)
- html-proofer (3.18.8

As apparently they didn't play nicely with the Ruby version I've tried.

It also
-  adds `Webrick` since I couldn't build without it either.

Before merging and to test, please try this locally to make sure it works in your enviroment.

### CODE REVIEW

**Comment by GBKS** [comment]
My site also wouldn't build anymore after restarting my Mac. This PR fixed it.

**Review by GBKS — APPROVED** [review]

**Review by johnsBeharry — APPROVED** [review]

**Comment by johnsBeharry** [comment]
@danielnordh could you test this out and approve before we merge?

**Comment by danielnordh** [comment]
Confirmed working for me. 

ruby 2.6.3p62
gem 3.0.3
Bundler version 2.1.4

**Comment by pavlenex** [comment]
Just tested this on a freshly-installed  Mac Air 2017, worked even with default Ruby `2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]`

**Pull request merged**
