### PR TITLE
Added security headers

### PR DESCRIPTION
**Pull request by pragya1976**
#915 
Designed header images for security section in Daily Spending Wallet.

figma link: https://www.figma.com/file/95gJ0esWcAoKAdULBmIAZT/Security-header?node-id=0%3A1&t=bPk8gEzBKbIGWCIG-1

Here is the reference sketch that I used to design this illustration:

security-header-rough-sketch

### CODE REVIEW

**Review by GBKS — CHANGES_REQUESTED** [review]
I have the [same feedback](https://github.com/BitcoinDesign/Guide/pull/1002#pullrequestreview-1377211971) as for #1002.

I think it's also a good idea to add a background color to the images, even if it's light, so the visuals don't float so much.

**Comment by pragya1976** [comment]
The required changes have been made. Please review

**Comment by GBKS** [comment]
Thanks you for the update, I have just a few more points:

The images half-transparent edges, could you please re-export them with crisp edges? Here's what I mean:

image

The desktop image is square and takes up the whole screen. Could you please adjust the layout to something like 1600x600?

image

I am not sure what the problem is, as the images works correctly in the browser, but macOS has problems with "security-header.png". Could you try to re-export it?

image

Thank you.

Also, when you reply here, I will receive an email notification so I will be aware of your updates.

**Comment by pragya1976** [comment]
ok sure .Will do necessary changes

**Review by sbddesign — APPROVED** [review]
Looking nice. Good design, and all the images appear to be correctly formatted to me.

**Review by sbddesign — CHANGES_REQUESTED** [review]
Actually, 2 details here. Like I mentioned in your other PR, add your figma link to the editor notes in the source code so it's preserved. Also, I do not see any entries in `_compress_images_cashe.yml`, which means the images have not been compressed for the word. You can do this by running the site site locally using `bundle exec jekyll serve` or `docker-compose up`. Alternatively, I can handle this for you if you and push it to your branch if you like.

**Comment by pragya1976** [comment]
@sbddesign thanks for the feedback. I will do the required changes.

**Comment by pragya1976** [comment]
@sbddesign I have added the figma links in the source code but I am unable to run the site locally. Please can you help me by 
creating entries of these images `_compress_images_cashe.yml`.

**Review by GBKS — APPROVED** [review]
ACK. I resolved the image issues.

@sbddesign could you please update your review?

**Pull request merged**
