### PR TITLE
Image for Design Source Files page

### PR DESCRIPTION
**Pull request by jakey-ads**
Thanks for bearing with. Still getting to grips with PRs and codebase stuff.
Referencing the issue here https://github.com/BitcoinDesign/Guide/issues/735
Link to [source file on Figma](https://www.figma.com/file/kmZVLnU6Bfwc01K7hCS7Qd/Banner-image-%7C-Design-source-files?type=design&node-id=453%3A1053&t=04N8RiCzKdbVgYZp-1)

### CODE REVIEW

**Review by GBKS — CHANGES_REQUESTED** [review]
That looks excellent, really nice work. Just have some tiny maintenance things.

- Please the `design-resources-preview.jpg` that you're replacing with your new one. Since it's no longer used, we can delete it.
- You don't need a `@2x` version of `design-source-files-preview.jpg`. Can also delete that one (meaning `design-source-files-preview@2x.jpg`).
- Include a link to your Figma file in the editors notes (in case anyone wants to build on it at some point).

Then it's ready to go, IMHO.

**Comment by jakey-ads** [comment]
@GBKS thanks! :)
Hopefully that's good now. I made the changes and think that's updated

**Review by GBKS — APPROVED** [review]
ACK. Thanks for the quick update. Ready to go from me, will just wait for one more review.

**Review by johnsBeharry — APPROVED** [review]
Looks very good to me. Awesome work and congrats on your first PR!

**Pull request merged**
