### PR TITLE
Formatting: Increased size of page content section headings.

### PR DESCRIPTION
**Pull request by Bosch-0**
Increased size of page content section headings. They looked too small before, especially on mobile. Below is before and after for desktop and mobile:

Frame 28

Also added the coming soon pages for onboarding in this PR.

### CODE REVIEW

**Review by pavlenex — APPROVED** [review]
I will merge this one so I can rebase #220 as agreed in #248

**Comment by pavlenex** [comment]
@Bosch-0 actually I shouldn't have merged this one probably, because the #220 lists these sections in a different way.

## With #249
Screenshot 2021-04-20 at 16 47 32

## Witth #220
Screenshot 2021-04-20 at 16 47 40

Which one do we prefer? I kinda prefer concise list vs headings which to some may not be that obvious are clickable. I'll rebase if we agree to go with whatever.

**Comment by pavlenex** [comment]
Sure thingy, I'll re-base #220 according to #249 and await for #231 later on, good idea.

**Comment by Bosch-0** [comment]
I'm more in favor of the headings. Agree with GBKS dot points look too condensed. In hierarchical terms using dot points makes it look lower, this list is the main content on this page and should be more prominent as @danielnordh mentioned in the comment link in OP. If we were use dot points here it would make sense to also change all the other section overview lists to this styling to keep consistency. 

I agree that the spacing could be decreased above the heading between the break, it should match the spacing between the body text and the break. I didn't touch that part of things in this PR as #231 is addressing that and it isn't a simple fix. We could remove the break and decrease margins to get a style like below:

Frame 31

**Comment by danielnordh** [comment]
The left picture looks good to me.

**Pull request merged**
