### PR TITLE
Iteration of the savings wallet case study page

### PR DESCRIPTION
**Pull request by GBKS**
savings-case-study-update-210712

[Preview](https://deploy-preview-428--sad-borg-390916.netlify.app/guide/case-studies/savings-account/)
[Video summary](https://youtu.be/wp7eoxSWmhE)

Makes the following changes:
- Updates UI mock-ups to use the [Bitcoin UI Kit](https://www.bitcoinuikit.com)
- Expands third-key functionality to auto-signing transactions for low amounts
- Adds send flows for low and high value transactions
- Adds key recovery flow
- Adds auto-signer limit change flow
- Restructures the page to better mix text and visuals
- Adds links to this case study from a few relevant pages

Would love to get feedback on:
- Overall impression, presentation and readability
- Level of detail included (enough technical detail? too many visuals?)
- Ideas for cross-referencing
- Flaws in the UX flows
- Writing
- Anything else that stands out

This PR is loosely based on the [discussion here](https://github.com/BitcoinDesign/Guide/discussions/418).

### CODE REVIEW

**Comment by pavlenex** [comment]
concept ack

**Comment by danielnordh** [comment]
Page looks good to me. 
I left some detailed comments in the Figma file that would be great to tackle before merging.

**Comment by ConorOkus** [comment]
This is looking good to me. I also left a few minor comments in Figma. 

Perhaps we want to include something about optionally being able to reset a pin using email or phone numbers.

The seems mergeable to me though, good job!

**Comment by GBKS** [comment]
Thanks for the feedback. I just pushed an update that should address it all.

As a follow-up task, I do think we need a page about hardware wallet interactions so we can help make users comfortable with multisig. This page could cover connection types (Bluetooth, QR, SD card), device types (signer-only, device with screen, etc), and how to handle common user flows. Luckily we already have an issue for this with #59.

**Review by danielnordh — APPROVED** [review]
Feedback addressed.
LGTM

**Review by ConorOkus — APPROVED** [review]

**Comment by GBKS** [comment]
Thank you for the reviews.

**Pull request merged**
