### PR TITLE
Moved the Bitcoin glossary from the Google doc to GitHub glossary.md file

### PR DESCRIPTION
**Pull request by Bosch-0**
Moved the content from https://docs.google.com/document/d/1_mG2GHfDe6UrVzL-HEoUMNluKkRzDHbcnrHy0Xz6GdM/edit# to the glossary.md file. Also added a few new additions and organized them alphabetically. 

I grouped some of the terminology to make it easier to find relevant info. An example being for nodes and wallets which I displayed like below. Thoughts? 

Node (Full)
Node (Pruned)
Node (Archival)

### CODE REVIEW

**Comment by GBKS** [comment]
Sorry, there's some overlap with this PR here where I had also moved the Google Doc into glossary.md: https://github.com/BitcoinDesign/Guide/pull/31

Let's see how we can merge these two. Looks you are using a table layout, does that look good on mobile?

**Comment by Bosch-0** [comment]
Sorry about that should have checked GitHub before making changes. Will fix this.

Doesn't look too bad. 

image

**Comment by GBKS** [comment]
It works when the description is a few words, but then it falls apart. Let's do some custom layout and interaction on this page to make the definitions collapsible. I'll mock it up tomorrow.

**Comment by Bosch-0** [comment]
Closing this duplicate PR, will include my changes in https://github.com/BitcoinDesign/Guide/pull/31

**Pull request closed without merging**
