### PR TITLE
Adding a wallet selector case study

### LINKED ISSUE #710: Linking prefixes for managing inter-app payments
Zeus recently merged a novel way to deal with inter-app payments on mobile (particualry for iOS which has UX issues with handling `bitcoin:` URIs) using linking prefixes. @tim-edwards from THNDR games was the one to put this idea forward. Details on how this work can be found in this issue https://github.com/ZeusLN/zeus/issues/888 and this PR https://github.com/ZeusLN/zeus/pull/889.

Essentially when an app needs to present payment request the user selects the app that they want to pay with. Behind the scenes Zeus THNDR searches from a unique Zeus prefix (see PR linked above) and interacts with Zeus through that bypassing iOS's URI handling scheme.

In the image below:

1. Zeus has been selected in THNDR games as the app to pay this invoice. Zeus had to add a handling prefix for this to be managed as mentioned above.
2. Zeus is automatically opened when clicking claim in THNDR games
3. Zeus autofills the payment request inputs and creates an invoice and shares it with THNDR to be paid.
4. THNDR pays the invoice <3 

image

Is this something we would want to cover in the guide? It isn't the most eloquent solution but iOS bitcoin app handling is probably a worse UX.

### PR DESCRIPTION
**Pull request by GBKS**
This is a new case study page for a UI pattern for choosing an external wallet to use when initiating a transfer in a bitcoin application.

⚒️[Check the preview](https://deploy-preview-1020--bitcoin-design-site.netlify.app/guide/how-it-works/wallet-selector/)⛏️

Closes #710

### CODE REVIEW

**Review by sbddesign — CHANGES_REQUESTED** [review]
This is great content that is needed! I made several grammar tweaks and fixed an incorrect link.

Nit: I feel like this belongs in the "How It Works" section. I have always thought of the Case Studies section as articles that focus on specific projects and how they solve problems. I guess the PayJoin one is a little different in that regard, but it does go into some detail about how BlueWallet accomplishes it. The conversations I remember when we first started the Case Studies section revolved around letting these be studies on actual projects in the wild. This content reminds me more of the stuff in the How It Works section.

**Comment by GBKS** [comment]
@sbddesign thanks for the feedback, I accepted all your suggestions. Regarding the section, I can go either way. Putting it in the `Case studies` section makes _very slightly_ more sense to me, but not going to argue if others feel strongly otherwise.

**Comment by danielnordh** [comment]
Great addition.

Regarding the location of the page.
I also feel that the 'How it works' section could be a good home, but I don't feel strongly enough to say you SHOULD put it there.

Regardless, it seems like this page could use some references to your new page:
https://bitcoin.design/guide/how-it-works/payment-request-formats/

**Comment by GBKS** [comment]
Thanks for the feedback. I moved the page to "How it works" (getting quite long, that section) and added cross-links to the payment request formats and requesting bitcoin pages.

**Review by danielnordh — APPROVED** [review]
LGTM

**Review by sbddesign — APPROVED** [review]
🏌️

**Pull request merged**
