### PR TITLE
Updated 'onboarding/Backing up recovery phrase' image

### PR DESCRIPTION
**Pull request by Bosch-0**
Solves issue https://github.com/BitcoinDesign/Guide/issues/417 

Also added editors notes to the source file for these images.

### CODE REVIEW

**Review by pavlenex — APPROVED** [review]

**Review by GBKS — CHANGES_REQUESTED** [review]
Could you please also update the height attribute of the image include?

**Review by pavlenex — APPROVED** [review]

**Comment by GBKS** [comment]
Sorry, I didn't mean the header image, but the include of the image you changed.

**Comment by Bosch-0** [comment]
Fixed, sorry edited on GH changed the wrong image </3

**Comment by GBKS** [comment]
Sorry, it's still not right.
- The image you replace is 542px tall but the include is set to 540
- `copy-recovery-phrase@2x.png` is 414x896. It should be exactly 2x the size of `copy-recovery-phrase.png`, which is 500x1084

**Comment by Bosch-0** [comment]
Updated

**Comment by GBKS** [comment]
I am sorry to keep bugging about this, but the most recent update resized the 1x image, so now both the 1x and the 2x images are the wrong size.

**Comment by Bosch-0** [comment]
No it's my bad sorry! Okay that should of done it :)

**Review by pavlenex — APPROVED** [review]

**Review by GBKS — APPROVED** [review]

**Pull request merged**
