### PR TITLE
Add an example to the descriptors glossary entry

### PR DESCRIPTION
**Pull request by GBKS**
There were some questions around what descriptors are in a recent call. The glossary entry does a pretty good job as is, but I think that having an example will help people better understand what this actually looks like.

Need to verify in PR review whether this descriptor is legit. I had a hard time piecing things together from the available documentation I found.

🤦🏻‍♂️[Check the preview](https://deploy-preview-1052--bitcoin-design-site.netlify.app/guide/glossary/#output-script-descriptor)🤦🏻‍♂️

### CODE REVIEW

**Review by thunderbiscuit — APPROVED** [review]
ACK 5132f27a60aede27e7f838922ade5c4ea7e5eb4a. Fantastic work! I love the comics.

The only nit I want to point out is a small typo in the example image where you can real "Extended prvate key...".

**Comment by GBKS** [comment]
@thunderbiscuit thanks for catching that. I updated the image.

**Comment by rabbitholiness** [comment]
Looks good to me. Having an example is great.

**Comment by mouxdesign** [comment]
Screenshot 2023-11-29 143322
Very good to add in an example, a simple image can make a huge difference in someone understanding a concept. 

- Minor suggestion would be to perhaps do the "Checksum for the descriptor" in another color as the grey and white could be tricky to differentiate for some. That said; white is on the front and grey at the tail end. So enough space between both to understand.

**Review by mouxdesign — APPROVED** [review]

**Pull request merged**
