### PR TITLE
Add bitcoin.design domain statement and signature

### PR DESCRIPTION
**Pull request by pedromvpg**
### Problem
- Ownership and assignment of the bitcoin.design domain to the bitcoin design community website.
### Solution
- As proposed by the community, as the holder of the domain, I'm adding a PGP signed statement committing the usage of the website for the use of the bitcoin design community.
### Todo
- Review statement language [here](https://github.com/BitcoinDesign/Guide/pull/21/commits/8580c504af320018af688c16448cc59c337aa3ab).
- Agree on what are the responsibilities of the domain maintainer.
- Find community members interested in maintaining the domain.
- Call out any other conditions that should be met before this domain is used.

### CODE REVIEW

**Comment by Bosch-0** [comment]
ACK

**Comment by johnsBeharry** [comment]
@pedromvpg as this is an important issue could you provide a bit more details in your PR.

I recommend the following headings.

```
### Problem
- State the problem/s being addressed
### Solution
- What is your proposed the solution
### Result
- How was it finally implemented?
- What parts are you requesting to be reviewed?
- How is it to be used?
```

**Comment by pedromvpg** [comment]
Hey @johnsBeharry!
Added to the description of the PR: https://github.com/BitcoinDesign/Guide/pull/21#issue-483257685

**Comment by BitcoinErrorLog** [comment]
Nothing can remove the fact that the domain owner can pull the rug someday, Nothing can remove the fact that only reputation can inform us on the likelihood of that happening. I don't have the time to fully vet Pedro and none of the alternatives have better rep with me, so this is sort of a non-issue as I see things.

It's great that he is willing to provide signed statements and the domain for use, and that is good enough for me, all things considered.

In the end, the community has to be ready to have any centrally controlled access point taken away or used maliciously, including GitHub. So I'd rather not focus too much on complicating the domain issue.

Sorry, if I'm missing anything by swooping in like this! 

My vote remains to use bitcoin.design as primary domain.

**Comment by pavlenex** [comment]
Concept ACK.

**Comment by moneyball** [comment]
Ideally the ownership of the domain would be more closer to "the community" than "an individual." The only way I know how to somewhat achieve this would be to form a new entity, create by laws and governance with the community in mind, and assign ownership of the domain to that entity. To date, no one has volunteered to form such an entity or draft such by laws.

If we proceed with an individual owning the domain, aspects I think we should consider include:

1. How much contribution has the domain owner given to the design community to date?
2. How much contribution do we expect from the domain owner in the future?
3. Is the domain owner committed enough, involved enough, and trusted enough by the community to be a maintainer?
4. Does the domain owner have a strong track record within open-source bitcoin?
5. What is the probability the domain owner may opt for financial gain in the future with the domain at odds with community needs? One indicator might be if the domain owner has invested a material amount of their own personal money to buy the domain.

Pedro and I have had several conversations throughout 2020. I like Pedro a lot and believe he can be a great contributor to this community. However, he has a full-time job and not a lot of time to contribute. He also spent quite a bit of his money on the domain.

I strongly believe in property rights, so I think Pedro can do as he wishes with the domain. However, unless several things were to change from the above list, I am not supportive of the community becoming dependent on his domain.

I hope we can find a way forward as I agree with others bitcoin.design is the best domain name choice. I have asked Pedro what he would need to see from such an entity in order to transfer ownership to it. If we are able to define something that works for the community and for him, then someone can prioritize creating that entity.

Note that the other domains under consideration are owned by me. I purchased them each for $12 with 100% intention of donating them to the community and for use of this community (as I've been working on the development of this community for over a year now as part of my full-time job). Nevertheless, risks of misuse in the future don't disappear because of that, so if we were to use one of my domains, the community would need to be comfortable with me owning it and how I measure up to the above criteria, or, some criteria the community developers.

**Comment by BitcoinErrorLog** [comment]
If the qualifier for who gets to be trusted is whether someone is rich already, or has contributed more, then, as the actual fountain of money that powers this community, that is a game designed for Steve/Square to win at will.

I see no meaningful reason to trust Square or Steve any more than Pedro, because my view is no option can be trusted unless it can be enforced, which requires a formal contract and formal entity. If that means a new entity must be formed, so be it. 

Otherwise, Square is better off formally asserting itself as owner/leader of this community, if not only for the sake of progress, and then buying/renting the domain from Pedro outright.

If a new entity is formed instead, then Square could make a 3-way agreement to rent the domain from Pedro for a term, while agreeing to give content control to the community entity. 

Maybe we should use all the domains, users can promote whichever one they want, and the official list of mirrors can be managed by the community in GitHub or such...

**Comment by danielnordh** [comment]
## An attempt to move this issue towards a resolution.

We all agree that we would like to use bitcoin.design as a domain for the community and the guide.
Most of us want one primary domain that we promote, but other domains can also point to the content in this repo for redundancy.

The open question remains who controls the domain management. 
The goal being to provide longterm stability and reduce future risk of repurposing of the domain.

### Who should manage the domain?
Going through the comments here, the latest community call and discussions in the community I have heard five options 
(brief descriptions of each available further down);

1. A legal entity we would have to create and maintain
2. An active maintainer of the community github - starting with @GBKS 
3. The original owner - @pedromvpg
4. The original owner, but we don't promote bitcoin.design as the primary domain
5. The owner of other domains in use by the community - @moneyball 

### Proposal
To move this forward I am proposing we **adopt option 2**; 
- An active maintainer of the community GitHub should manage the domain, starting with @GBKS.

While it is my personal preference I know that there is support for this among people who have actively contributed to the community repos thus far. I also know that this option has been discussed with @pedromvpg and that he is OK with it.

### Action required
In order to conclude this in a timely manner please comment before December 2 with;
- **ACK - Option #2**, if you are supportive of this proposal
- **NACK - Option #2**, if you DO NOT support this proposal

If NACK, please provide a rationale and an alternative option you would support instead.
We will use the ACK/NACK responses to make a decision by rough consensus and wrap this issue up.

---

You can find much discussions of the above proposals further up in this thread but here is my attempt at brief summaries;

**1. A legal entity**
The main benefit of this approach is that the legal owenership and practical managament of the domain does not rest with one person alone.
The main drawback is the considerable effort, time and cost to create and maintain such an entity. 
It still would not protect from rogue actions by entity/domain maintainers and recourse would be through legal means.
This has been described in depth in [this document](https://docs.google.com/document/d/18UrtRONlwt8gjT1zyQE0kFs26E-J_gQTiNybxbysHd0/edit?usp=sharing). If you favor this option over others you should be prepared to do the work required to make it happen.

**2. An active maintainer of the community github**
The main benefit would be that the domain is managed by someone who has engaged and contributed actively to the community over time. 
The downside is that this is still a 'single point of failure' should the maintainer go rogue.
The duty/role of maintaining the domain would not be permanent and should not be thought of as ownership. 
A disengagement from the community would mean handing over the role to another active github maintainer.
Described more in this comment: https://github.com/BitcoinDesign/Guide/pull/21#issuecomment-699671395

**3. The original owner**
The main benefit is that nothing needs to change.
The main downside is unresolved concerns about one individual owning the domain while not being actively engaged on an ongoing basis.
These concerns are also outlined in this comment: https://github.com/BitcoinDesign/Guide/pull/21#issuecomment-699671395

**4. The original owner, but we don't promote bitcoin.design as the primary domain**
The main benefit is that nothing needs to change. It would also make the community less reliant on one single domain (with the idea that several others would also be used, up to the community members which they use).
Same downsides as 3, with the addition that UX around what domain to promote and where to find our content would be negatively impacted.
Proposed at community call #6 and discussed in this comment: https://github.com/BitcoinDesign/Guide/pull/21#issuecomment-699761330

**5. The owner of other domains in use by the community**
The main benefit would be that the domain would be managed by a person we already explicitly trust to own and maintain the original domain used to incept the community, the community Slack and without whom we would not be here.
The drawback is that it is centralizing control further and is not particularly community minded.

**Comment by ConorOkus** [comment]
ACK

**Comment by moneyball** [comment]
ACK - Option 2

**Comment by Thorbjoern** [comment]
ACK - Option #2

**Comment by pedromvpg** [comment]
ACK - Option #2
Open to transfer the ownership to someone more deeply involved with the project.

**Comment by Bosch-0** [comment]
ACK - Option #2

**Comment by johnsBeharry** [comment]
ACK - Option #2

**Comment by pedromvpg** [comment]
@moneyball, is Square Crypto still available to take the cost and finders fee discussed in the past to move ownership to a more active/permanent participant in the project?

**Comment by moneyball** [comment]
@pedromvpg Yes

**Comment by Rspigler** [comment]
These are my thoughts, although I realize I am not very active in this community:

I agree with option 2; although I think it should be someone separate than whoever owns the BitcoinDesign github - who at any time could remove other members/maintainers.  If not already, whoever this person is should be a trusted member of the community, and other individuals should work on mirroring the Github info to minimize the dependency on both this individual and Github itself.

I applaud the attempt at transparency but I think it comes at too much of a security risk.  Every crypto project has this centralization risk (Bitcoin Core too), and do you know which individual runs the Github and domain for those projects? The people necessary do, but not the general public.  If I were to be selected to manage the domain (which I won't be and I'm not asking) - I would only do it with the requirement that as few people know as possible. Otherwise, it opens you up to unnecessary targeting.  You can't social engineer an unknown.

**Comment by danielnordh** [comment]
As we are now past the deadline for the [proposed resolution](https://github.com/BitcoinDesign/Guide/pull/21#issuecomment-729798466) to this issue, I'll summarize responses.

We had 6 ACKs for **Option 2** - an active maintainer of the community GitHub, starting with @GBKS  
No NACKs, or ACKs for other options. 

It's therefore easy to conclude that **this proposal has passed**.

We had a further [comment](https://github.com/BitcoinDesign/Guide/pull/21#issuecomment-736837487) from @Rspigler supporting Option 2, and raising several valid points.

- Publicly sharing who the manager of a domain is comes with security drawbacks
- To reduce centralized dependencies further, the domain manager could be someone that does NOT have ownership of the community GitHub account

I agree that public knowledge of the domain manager is not ideal from a security point. While we have chosen to lean towards transparency here we can be open to improving this going forward if we can find a workable solution. Similarly with reduced centralization, happy to move in this direction over time, at this nascent time in the community it neither seems feasible (few candidates) nor a huge risk. 

I have written a first version of [rules for the managing of community domains](https://github.com/BitcoinDesign/Meta/pull/50), which any maintainer would have to adhere to, and which we can improve and update over time.

Thanks to everyone who worked on this issue and contributed time and thoughts. 
Especially @pedromvpg @moneyball and @GBKS who have done actual work outside GitHub.

**Comment by danielnordh** [comment]
Closing this PR. 
Going forward anything domain-related should be discussed in [meta/domains.md](https://github.com/BitcoinDesign/Meta/pull/50)

**Pull request closed without merging**
