### PR TITLE
Added Skip to content button + other a11y fixes

### PR DESCRIPTION
**Pull request by GBKS**
Looking to tackle various accessibility issues with keyboard navigation and voiceover.

- For the "Skip to content", see more info [here](https://webaim.org/techniques/skipnav/) and [here](https://css-tricks.com/how-to-create-a-skip-to-content-link/).
- Fixed some issues where JS didn't properly handle aria properties to indicate expanded/collapsed menus (see [aria-expanded](https://www.w3.org/WAI/GL/wiki/Using_the_WAI-ARIA_aria-expanded_state_to_mark_expandable_and_collapsible_regions#Example_1:_Using_a_button_to_collapse_and_expand_a_region)).
- CSS fixes to use focus-visible so elements are properly highlighted when using keyboard navigation ([info](https://stackoverflow.com/a/45191208) and [rationale](https://www.a11yproject.com/posts/never-remove-css-outlines/)).
- CSS fixes for some hover states.

Keeping this a draft, as I will probably find more issues with testing. Would also appreciate if others could test on various devices and provide feedback.

🧶[Check the preview](https://deploy-preview-770--sad-borg-390916.netlify.app/guide/)🎩

### CODE REVIEW

**Comment by Mogashni** [comment]
This is so nice to see! I found a whole checklist for web accessibility standards. It's something that also interests me. Am happy to pull out the main key points from these guidelines and put them into a list form and then look at how from a practical perspective these guidelines can be analyzed on the page. https://www.w3.org/TR/wcag-3.0/

**Comment by GBKS** [comment]
Let's also add support for [prefers-contrast](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-contrast) here.

**Comment by Mogashni** [comment]
Completed a voice over text on the bitcoin.desig/guide page using [NVDA](https://www.nvaccess.org/download/?msclkid=7361dd96cf8f11ecaa831a780f461e69). Here are the test results:
https://docs.google.com/document/d/1P9ofmOyztIfaSMm0dW5fpB6NlVnN1azUuHR99Tnb3Dg/edit?usp=sharing

**Comment by jason-me** [comment]
> This is so nice to see! I found a whole checklist for web accessibility standards. It's something that also interests me. Am happy to pull out the main key points from these guidelines and put them into a list form and then look at how from a practical perspective these guidelines can be analyzed on the page. https://www.w3.org/TR/wcag-3.0/

WCAG 3.0 is an interesting spin and I would definitely keep it in mind, but in the meantime would recommend[ WCAG 2.1 AA ](https://www.w3.org/TR/WCAG21/)(Which are the current guidelines) or even [WCAG 2.2 ](https://www.w3.org/TR/WCAG22/)which should be finalized soon.

Here is an explainer: https://uxdesign.cc/wcag-3-0-what-you-need-to-know-about-the-future-of-accessibility-standards-2e1f6374f2c7

**Comment by jason-me** [comment]
> Looking to tackle various accessibility issues with keyboard navigation and voiceover.
> 
> * For the "Skip to content", see more info [here](https://webaim.org/techniques/skipnav/) and [here](https://css-tricks.com/how-to-create-a-skip-to-content-link/).
> * Fixed some issues where JS didn't properly handle aria properties to indicate expanded/collapsed menus (see [aria-expanded](https://www.w3.org/WAI/GL/wiki/Using_the_WAI-ARIA_aria-expanded_state_to_mark_expandable_and_collapsible_regions#Example_1:_Using_a_button_to_collapse_and_expand_a_region)).
> * CSS fixes to use focus-visible so elements are properly highlighted when using keyboard navigation ([info](https://stackoverflow.com/a/45191208) and [rationale](https://www.a11yproject.com/posts/never-remove-css-outlines/)).
> * CSS fixes for some hover states.
> 
> Keeping this a draft, as I will probably find more issues with testing. Would also appreciate if others could test on various devices and provide feedback.
> 
> yarn[Check the preview](https://deploy-preview-770--sad-borg-390916.netlify.app/guide/)tophat

Nice job on the skip link, aria properties, and focus-visible. One thing I would also recommend is making the hidden skip link visible on focus for keyboard-only users so they can also see it when they are tabbing through the page.See: https://webaim.org/techniques/skipnav/

For the expand/collapse controls it may also be helpful to consider using the accessible design pattern for accordions from [WAI-ARIA Authoring Practices 1.2 ](https://w3c.github.io/aria-practices/#accordion)

**Comment by GBKS** [comment]
@jason-me thanks for the feedback. I just tweaked the "Skip to content" button, it now smoothly slides in from the top when focused.

The expand/collapse interaction is for the mobile navigation, which covers the full screen when expanded. I've been looking at the "[menu button](https://w3c.github.io/aria-practices/examples/menu-button/menu-button-links.html)" guidelines for this, that's appropriate, right? With the last commit, I added `aria-haspopup` and keyboard up/down/escape logic to this.

I removed draft status from this PR now. It's ready for more thorough review and input, as I feel like I am not really able to push this much further at the moment without more feedback.

**Comment by jason-me** [comment]
@GBKS the "Skip to content" button looks great and is now exhibiting the expected behavior.

For the expand/collapse interactions on mobile you could certainly use a menu button, but then you would also need to add a `role="menu" `to the container for the list of links and add `role="menuitem" `to each.

The current implementation is closer to a dicslosure-navigation hybrid which is a bit simpler but probably a better pattern to go with: https://w3c.github.io/aria-practices/examples/disclosure/disclosure-navigation-hybrid.html

In this case, I would just add an `aria-current="page" `to the currently selected link so that screen reader users know which page is currently selected. Great work so far! 

I will try to provide more thorough review soon to address other low hanging fruit, but this is moving in the right direction.

**Comment by GBKS** [comment]
I was wondering whether `role="menu"` and `role="menuitem"` are necessary since the menu already uses the `nav` tag already?

I just added the `aria-current="page"` indicators.

**Review by sbddesign — APPROVED** [review]
- Verified the Skip to Content link works when using a screenreader
- Verified I can toggle menus open and closed with keyboard while navigating with a screen reader
- Verified I can tab between links and clickable elements

I am basically just testing the features that you have added in this PR. Is there anything else I should be looking for?

We might want to go page-by-page and [check some things with the WAVE tool](https://wave.webaim.org/report#/https://bitcoin.design/). That could inform future issues and PRs. For example, I opened #831 because of a WAVE test.

**Comment by jason-me** [comment]
@sbddesign WAVE is cool and easy, but you should also check out out [ARC Toolkit ](https://www.tpgi.com/arc-platform/arc-toolkit/ and [AXE](https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd?utm_source=deque.com&utm_medium=referral&utm_campaign=axe_hero) when you have a chance.

**Comment by GBKS** [comment]
Thanks for the review. Going to merge this one for now, and we can tackle additional accessibility tweaks in future PRs. With accessibility, I find it difficult to be 100% sure that everything is covered as I don't have the expertise/experience. Step-by-step iteration is the way to go, IMHO.

**Pull request merged**
