### PR TITLE
Update Gemfile.lock

### PR DESCRIPTION
**Pull request by GBKS**
So GitHub auto-created PR #1072 as a security update. My local dev environment no longer worked with this. After around 6 hours of trying to fix it myself (always seemed to come down to Ruby compilation problems related to OpenSSL versions), I bought Ruby on Mac and used it to completely reset my local dev environment and move to a newer version of Ruby (3.2.3). Now it works again.

To be honest, I do not really understand all this build and dependency stuff and might be getting things wrong. Any input appreciated.

We have not updated this lock file in years, maybe it's a good time to push this update so we use the latest version of Ruby and various dependencies? But first we should have a few people test this. Maybe it's just me having all these problems.

To get this to work on Netlify, I also had to add a `.ruby-version` file that declares which ruby version to use. Otherwise it tried to somehow figure out which version to use and picked one that didn't actually work.

To make it work in Docker, I had to remove the automated image compression (irreconcilable dependency issues). We'll just have to manually do this for now, and see if there is a better solution out there. The image compression cache file cache file caused issues all the time anyways, so we're just trading one thing for another (manually compression them).

To help test this, download this pull request, then run `bundle install` and `bundle exec jekyll serve`. This assumes you have a Mac and ruby installed. I have no clue how things work on Windows.

### CODE REVIEW

**Comment by johnsBeharry** [comment]
I had made a docker compose file. If you have docker installed, it should work fine. Haven't tested in a while though, will give it a go against PR

**Comment by GBKS** [comment]
@johnsBeharry it did not work. So I removed the image optimization stuff. Just got constant issues with the `image_optim` dependency, no mater what combo of other things I used (ruby versions, jekyll image versions, bundler versions, image_optim versions, etc). 

As is, this PR "should" (maybe) work locally and in Docker. Maybe we need to find a different image compression solution, or just do it manually (the compression cache file was a constant hassle anyways).

**Comment by GBKS** [comment]
Totally. But it's also a good practice for designers to compress images generally, using a tool like [image optim](https://imageoptim.com/mac) or so. So I'm cool with merging this one (after more testing), and then finding a compression solution later.

**Review by mouxdesign — APPROVED** [review]
Tested on my local environment with Github desktop and Docker and was able to view the deploy preview.

**Pull request merged**
