### PR TITLE
Revised images in the User Research page

### PR DESCRIPTION
**Pull request by GBKS**
Using a flat style with bright colors to match the page header.

Frame 91

### CODE REVIEW

**Review by johnsBeharry — DISMISSED** [review]
This one is a bit much for me I'm not going to lie. Don't think I'm digging the greys.

Still an improvement though, can keep this PR open a bit longer to see if anyone else has some input. Otherwise here's the approval.

**Comment by GBKS** [comment]
@johnsBeharry tell me more. What about the grays bothers you? Any other details you don't like?

**Comment by johnsBeharry** [comment]
So I know we don't necessarily have to make styles match between the header and content images, but it seems like this is what was being attempted so I'm going to comment on that.

- the header uses a creamy colour, while the content images use a grey in the background.
- the colourful humpgraph is really distracting
- minor point: style of the header is marker felt and sticky notes while the in page illustrations are more straight cut.

_funny enough the original black and white images on this page, have this unfinished feel - which I think also kinda works with the marker / whiteboard header._

**Comment by GBKS** [comment]
@johnsBeharry thanks. I did some minor color adjustments for a little more consistency with the header. Decided to keep the in-page images more finished-looking for consistency across all the other images of that style (which are spread across a ton of pages).

**Review by pavlenex — APPROVED** [review]
tACK https://github.com/BitcoinDesign/Guide/pull/303/commits/6f3e1992cda63104dfd678ecf288a9691a5fc7ae

**Pull request merged**
